### ISSUE TITLE
overlay stops working when switching apps.

### ISSUE THREAD

**Issue by RaptorX** [Alia5/GlosSI#108]
I created a desktop profile, and imported my current settings to the steam shortcut by GloSC.

Everything works as expected until I hit Win+Tab to switch to another program like Chrome or anything else. after that the notification when changing sets stops working. the only way to fix is restarting the shortcut.

**Comment by Alia5** [comment]
Can you try https://github.com/Alia5/GlosSI/releases/tag/0.0.2.0
