### ISSUE TITLE
Monitor pitch black after exiting full screen application .

### ISSUE THREAD

**Issue by 8bitnectar** [Alia5/GlosSI#115]
I've been having this issue lately on a fresh install. Everything is working fine but after exiting the game the entire monitor goes black. Ctrl+alt+dlt  doesn't change it, alt tab doesnt either, the only thing that fixes it is to close glosc from the task bar on a separate monitor. 

It's not the biggest deal because it's fixable with a reboot of the glosc shortcut but I'm curious if anyone knows what's going on and if there is a fix for thisissue?

Thanks!

**Comment by DrPepperBianco** [comment]
I'm also having this problem. As far as I understand, this only happens, if the resolution changes. Like you have Full-HD (1080p) screen, but your Full Screen game only running on 720p or so. Then the GloSC overlay becomes black.

I assume it is the GloSC overlay. Meaning, the program Steam thinks it is running.

**Comment by Alia5** [comment]
GloSC: Set the shortcut config to "windowed mode"


GlosSI: fixed
