### ISSUE TITLE
GloSC only pulls UWP app list from the admin account used to elevate

### ISSUE THREAD

**Issue by stukindaguy** [Alia5/GlosSI#123]
Right now GloSC only pulls the list of UWP apps from the administrator account used to launch it, rather than the list from the currently logged in user and I cannot find a way to manually do this.

**Comment by crsnplusplus** [comment]
@stukindaguy I think I found a workaround for this: 
navigate into your GloSC/target folder ( `C:\Program Files (x86)\GloSC\targets` by default), and create a new UWP game using the button UWP.

A new .ini file will be created under `target ` folder, edit the filename with the name you would like to see in Steam, and fix the path with the path of your UWP.

This is the .ini file for GloSC I use to run Octopath Traveler (Gamepass), from Steam using a Steam controller:

```

[BaseConf]
bEnableOverlay=1
bEnableControllers=1
bUseDesktopConfig=0
bHookSteam=1
version=518

[LaunchGame]
bLaunchGame=1
Path=39EA002F.FrigateMS_n746a19ndrrjg!Game
Args=
Type=UWP
bCloseWhenDone=1

```

As you may have noticed for some reason Octopath Traveller UWP name is `39EA002F.FrigateMS_n746a19ndrrjg!Game` which is not very expressive and is quite hard to figure out. Here is what you can do if you are in a similar situation:

open your Application folder, by running this folder either in run, or directly in explorer:
`%windir%\explorer.exe shell:::{4234d49b-0245-4df3-b780-3893943456e1}` (I know, it sounds dodgy, if you find a better way to reach it, please let me know! :) )

The folder will show all your UWP applications, right-click on the one you want to know the name of, and create a desktop link.
This way you will only see the name of your application, but AFAIK you will not be able to copy it.

If you are lazy like me and you cannot be bothered to copy it by hand, you can:
- create a shortcut in steam using UWPHook ( you should be able to recognize the name from the desktop link you just created )
- relaunch steam
- open the properties of the shortcut in steam, copy the name from there
- remove the UWP link from steam

and then as before:
- create a .ini file in your GloSC/target folder
- copy the contents below in the newly created .ini file
- replace the path with your path copied from 
- launch GloSC and add the game in Steam

let me know if this works for you! :)

**Comment by mikew** [comment]
This is a pretty annoying process, so I went a weird way and wrote a powershell script that filters UWP apps by version. It goes by version number because it needs _something_ to filter by, and the version of a UWP app is quick and easy to get.

https://gist.github.com/mikew/9a122f2d86d9ae75e66fbcd0dc7ccd33

To find an app's version, all you need to do is type the name of the app into the start menu and select "App Settings".

**Comment by gbdrbob** [comment]
> This is a pretty annoying process, so I went a weird way and wrote a powershell script that filters UWP apps by version. It goes by version number because it needs _something_ to filter by, and the version of a UWP app is quick and easy to get.
> 
> https://gist.github.com/mikew/9a122f2d86d9ae75e66fbcd0dc7ccd33
> 
> To find an app's version, all you need to do is type the name of the app into the start menu and select "App Settings".

That's cool but a bit overcomplicated. Are you aware that `Get-StartApps` will give you the AppID of any app in the start menu, without having to reconstruct it from the manifest file?

e.g 
`Get-StartApps | select name,appid | where {$_.name -Like "psychonauts 2"}`

![image](https://user-images.githubusercontent.com/17690288/131215224-fdffdf41-f31e-4e82-b476-bab8d7a56256.png)

That allows a simpler version of your script to be created that filters on the actual game name (or a wildcard of the name):

```
param (
    # Either run this as a script and pass a `-game` parameter, or write the
    # game name below and copy/paste the contents of this file in PowerShell.
    [string]$game = "Psychonauts 2"
)

$gamedetails = Get-StartApps -Name "$game" `

Write-Host " `
$($gamedetails.name).ini `
 `
[BaseConf] `
bEnableOverlay=1 `
bEnableControllers=1 `
bUseDesktopConfig=0 `
bHookSteam=1 `
version=518 `
 `
[LaunchGame] `
bLaunchGame=1 `
Path=$($gamedetails.appid) `
Args= `
Type=UWP `
bCloseWhenDone=1 `
"
```

Note no checking is done whether your wildcard matches more than one app, if it does you'll get an invalid ini file

**Comment by mikew** [comment]
Awesome! I’ll change it so it prints a configuration for each found app.

**Comment by mikew** [comment]
I've updated the script in the gist, thanks again for those tips.
