### ISSUE TITLE
Steam link white or black screen

### ISSUE THREAD

**Issue by manporde** [Alia5/GlosSI#127]
Hi,

I'm trying to use glosc with steam link, when launch the game added in my steam library the sreen in my mobile get white or black, but sounds run even I can choose options(the game sounds when you move on the options) in the game, but the screen keep in white. I could stop the game in steam options, and the screen white dissapears and the game show on, but then the gamepad can't used and the controls become keyboard and mouse. I tought that the glosc works up the game, maybe a transparent screen put on the game, but with the steam links doesn't work. Couldd it be fixed?

**Comment by Alia5** [comment]
GloSC/GlosSI is not a steam remote play solution
