### ISSUE TITLE
Steam stops responding after a GloSC overlay closes.

### ISSUE THREAD

**Issue by JediRhymeTrix** [Alia5/GlosSI#128]
Hi,

I've been facing an issue recently when closing a GloSC enabled game where the Steam Controller disconnects from Steam and goes into lizard mode and the Steam BPM stops responding. The only way to recover is to force close all steam processes from Task Manager and restart Steam client.  The same thing also happens if the SC disconnects while playing a game launched via GloSC.

I'm not entirely sure whether this is a GloSC issue or a Steam issue, but everything seems to be working fine for native steam games and regular non-steam shortcuts.

**Comment by maicol07** [comment]
I  also have this issue

**Comment by maicol07** [comment]
Actually, I've found a workaround for this issue: simply click "Restart Steam" or "Close Steam" from Steam file menu at the top of the window

**Comment by Alia5** [comment]
Can you try https://github.com/Alia5/GlosSI/releases/tag/0.0.2.0
