### ISSUE TITLE
Log Spam when process exits/PID changes even when not set to quit.

### ISSUE THREAD

**Issue by Alia5** [Alia5/GlosSI#132]

**Comment by BlacRyu** [comment]
![Screenshot 2021-11-09 14 26 43](https://user-images.githubusercontent.com/10762433/141016035-f4d9ffbc-8ded-4c47-a5a7-64d789b33f16.png)
Same issue here when config is set to not close on app quit. Controllers seem to work fine but I seem to lose the ability to see half my screen

**Comment by Alia5** [comment]
https://github.com/Alia5/GlosSI/commit/f5b71bf9c9a91adcbff088ed7eacb79992911e87
