### ISSUE TITLE
Detect if an app opened another app

### ISSUE THREAD

**Issue by LordBoos** [Alia5/GlosSI#134]
It would be great if GlosSI could detect if an app opened another app and hook into that new one as well.
I mostly use GloSC and now GlosSI for UWP games from Xbox GamePass and those generally have kind of a "launcher screen" that launches the game itself. Problem is that GlosSI hooks into that launcher and once it actually launches the game then GlosSI either closes or starts spamming process PID died if set to not close on game exit.

If possible, GlosSI needs to detect the PID of the application that the launcher started and hook into that.

This is a "launcher screen" when I start the shortcut:
![image](https://user-images.githubusercontent.com/939813/141105943-9ffc117e-d821-4738-8c5a-6855479dc84c.png)
This is when the "launcher screen" closes and game actually begin to start:
![image](https://user-images.githubusercontent.com/939813/141106042-a31a400f-170e-4e4e-96b6-008a7fafcb6d.png)
This is when the game starts and goes to main menu:
![image](https://user-images.githubusercontent.com/939813/141106371-deb549a9-0eaf-43f7-8369-34ebda9f6c33.png)

**Comment by Alia5** [comment]
The logspam is a known issue. See 132

Watching a different process than launched is already requested. See: 53

And just to clean up misconceptions: 
Also GloSC/GlosSI doesn't hook into any games. GloSC (optionally) hooks into Steam, GlosSI (optionally) hooks into windows explorer
That's it
