### ISSUE TITLE
GlosSI resets control layout to Desktop if parent process dies

### ISSUE THREAD

**Issue by Marocco2** [Alia5/GlosSI#135]
GlosSI 0.0.3.1
Controller - Steam Remote Controller
Game - Forza Horizon 5

What happens:
GlosSI won't keep standard xinput layout after FH5 launcher and it will restore Desktop layout

What should happen:
GlosSI should keep xinput layout until all child processes dies

**Comment by Marocco2** [comment]
May due to #53 but I felt this issue should be noticed

**Comment by Alia5** [comment]
Anything other I could test/debug this with other than the Windows Store version of FH5 (I have it on Steam and won't buy a second copy)

**Comment by Marocco2** [comment]
> Anything other I could test/debug this with other than the Windows Store version of FH5 (I have it on Steam and won't buy a second copy)

Perhaps Halo Infinite which should be free to play

**Comment by mikew** [comment]
I've used GlosSI on a few gamepass games:

- Forza Horizon 5
- Unpacking
- Minecraft Dungeons

Only FH5 exhibits this weird bug where it constantly shifts between keyboard and controller inputs. Unpacking and Minecraft Dungeons were fine.

**Comment by DiamondNinjaX** [comment]
Is this issue fixed for FH5? 
I know it still says open, but  GloSC doesn't work and the GlosSI Target window just closes after 10-15 minutes of gameplay, rendering my controller unusable. Bit frustrating 😆

**Comment by Alia5** [comment]
@DiamondNinjaX 
What you can try is unchecking "Close when launched app quits"
Then GlosSI Target shouldn't close...

**Comment by DiamondNinjaX** [comment]
@Alia5 
Just tested it again, the setting is unchecked but the issue still occurs.
Game doesn't crash nor does controller disconnect from PC, but in-game it just says "controller disconnected".

**Comment by Marocco2** [comment]
> Is this issue fixed for FH5? I know it still says open, and that it's being written, but GloSC doesn't work and the GlosSI Target window just closes after 10-15 minutes of gameplay, rendering my controller unusable. Bit frustrating 😆 Maybe someone else has found a fix other than Alia5?

Yes, it's still present.
A workaround I found is open and close steam overlay to get controls back

**Comment by DiamondNinjaX** [comment]
> > Is this issue fixed for FH5? I know it still says open, and that it's being written, but GloSC doesn't work and the GlosSI Target window just closes after 10-15 minutes of gameplay, rendering my controller unusable. Bit frustrating 😆 Maybe someone else has found a fix other than Alia5?
> 
> Yes, it's still present. A workaround I found is open and close steam overlay to get controls back

This doesn't work. Shift+Tab does nothing, as the "game" (GlosSITarget.exe) closes and thus Steam doesn't do anything.

**Comment by Alia5** [comment]
Just read this on Discord
Maybe it's just Steam, then?

> RambleTan — Yesterday at 4:13 PM
I feel like it's been just with the most recent stable steam client but I'm having to frequently push the Home button twice to reload my game config.
Like, accessing BPM and then exiting, the config stays loaded for about 5 seconds and then kicks into the desktop config (I think, clearly not my game saved config).
Anyone else noticing this?
Seems like maybe it's specific to non-steam shortcuts.

**Comment by Marocco2** [comment]
That's interesting. Unfortunately I can't test this ATM

**Comment by Pixelramp** [comment]
Same for me in Forza Horizon 5 Game Pass version.

The the workaround does not work for me..
