### ISSUE TITLE
GlosSI Overlay obscures view of game

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [Alia5/GlosSI#138]
Hi, first of all thanks for updating this excellent project. I'm currently using it successfully with Halo Infinite.

I tried looking for an option to hide the GlosSI overlay that comes up every time I go into the steam overlay and stays for a while over the game obscuring game play. It could do with an option to turn it off or make it transparent. Maybe a smaller version of it would help that appears in the corner of the screen ?

Cheers.

**Comment by Alia5** [comment]
In `%Appdata%\Glossi\Targets` you can set the overlay scale for each configuration there.  
i.E.  `%Appdata%\Glossi\Targets\HaloInfinite.json`:
```json
{
...
    "window": {
        "maxFps": null,
        "scale": 0.5, // <-- would scale everything down to 50%
        "windowMode": false
    }
}
```

Additionally, you can just set it to windowed mode.  
Either via GlosSIConfig or also in the target.json files

**Comment by Michael-Z-Freeman** [comment]
Thanks for the setting. 

I'm pretty sure it's opening every time. I'll check that again and put in an issue if necessary.
