### ISSUE TITLE
AMD control panels shows running game named as GlosSI. Effect on AMD driver optimisations ?

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [Alia5/GlosSI#139]
Hi. When I start Halo Infinite (UWP) it shows as "GlosSI" in the games section of the AMD control panel. AMD recently released drivers with a performance boost for Halo Infinite. If AMD is not seeing the actual game directly, but rather GlosSI, will this affect the way AMD applies optimisations to the actual game ? I've tried adding the exe directly to AMD but it does not have the correct permissions even with the new insiders Xbox app which allows installation to any folder with some reduced permissions. I did start Halo directly from the Xbox app (no GlosSI or steam) and could not see any improvement in performance but this does not really prove much without a benchmark.

**Comment by Michael-Z-Freeman** [comment]
OK, can you explain the reasoning here? Other similar utils such as UPHook pass through the exe name. I just did some research. Apparently AMD applies driver optimisations based on the executable name although I could not find an official source for that. There could be some way to change the exe name that triggers the profile by editing AMD XML but it looks fiddly to say the least.

**Comment by Alia5** [comment]
> Other similar utils such as UWPHook pass through the exe name.

Those tools don't create a window where stuff gets rendered to 60 times a second that behaves like it were a game.
GlosSI needs to do this however to provide overlay-functionality without hooking.

**Comment by Michael-Z-Freeman** [comment]
OK, thanks. I confirmed that my worries were unwarranted as AMD released a driver that added Game Pass support ...

"Most likely the Game Pass games have a different folder structure / exe name so the old fixes weren't being applied, same as if you rename the exe to bypass them. So they just updated the name checking / added those to the profile lookups."

https://www.reddit.com/r/Amd/comments/bypg4m/comment/eqo41xm/?utm_source=reddit&utm_medium=web2x&context=3
