### ISSUE TITLE
GlosSI crashes when trying to add UWP app

### ISSUE THREAD

**Issue by matzase** [Alia5/GlosSI#140]
Hi,
I am trying to add Forza Horizon 5 from XBOX game pass to GlosSI but when I select UWP APP, Select UWP APP... window appears, looks like it is starting to load a list, but then whole GlosSI crashes.

**Comment by Alia5** [comment]
Should be fixed https://github.com/Alia5/GlosSI/commit/6b7127e1bb9713185d5d08c48e0bb1f9c96f4fc4

Download snapshot: https://ci.appveyor.com/project/Alia5/glossi/build/artifacts
