### ISSUE TITLE
Add sorting and fulltext search to UWP app list

### ISSUE THREAD

**Issue by LordBoos** [Alia5/GlosSI#141]
UWP app list is kind of a mess sorted by default by the time of an installation.
Please add some kinds of sorting that I can toggle, like sorting by name, installation date and so on.
Also fulltext search would be awesome when searching for specific game.

**Comment by Alia5** [comment]
Done ;)
https://github.com/Alia5/GlosSI/commit/35a47b03aaa53f5ec99dfd359ca6f51198ec6cd8
