### ISSUE TITLE
Clicking Select UWP App crashes program.

### ISSUE THREAD

**Issue by supraman215** [Alia5/GlosSI#142]
Either selecting it from the main menu or selecting it next to the browse option after trying manually crashes the program and forces it to reset.

**Comment by Alia5** [comment]
Log file in %appdata%\GlosSI ?

**Comment by supraman215** [comment]
[glossiconfig.log](https://github.com/Alia5/GlosSI/files/7842325/glossiconfig.log)

**Comment by supraman215** [comment]
[glossitarget.log](https://github.com/Alia5/GlosSI/files/7842534/glossitarget.log)

**Comment by Alia5** [comment]
> [glossiconfig.log](https://github.com/Alia5/GlosSI/files/7842325/glossiconfig.log)

Don't see anything special here... BTW: Which version did you use?



> [glossitarget.log](https://github.com/Alia5/GlosSI/files/7842534/glossitarget.log)

Seems like you missed installing HidHide

**Comment by supraman215** [comment]
HidHide is installed.
![image](https://user-images.githubusercontent.com/35738510/149673556-90992156-a3cc-4aef-8410-bd17f06a9abe.png)

**Comment by robsdedude** [comment]
Same issue here. Version `0.0.4.1`

Steps to reproduce:
 * (installed `HidHideMSI.msi` and `ViGEmBusSetup_x64.msi` that came bundled in the zip)
 * Start `GlosSIConfig.exe`
 * Click the blue plus button
 * select "UWP APP"
 * Outcome: program hangs on this screen (unresponsive) ![image](https://user-images.githubusercontent.com/4061254/150444762-cea85cdd-bfb4-4fa9-bd21-8ded6991a7fe.png)

Logs are very unspectacular.
```

[Fri Jan 21 01:39:05 2022] Warning: qrc:/qml/ShortcutProps.qml:155:17: Unable to assign null to QUrl
[Fri Jan 21 01:39:33 2022] Warning: qrc:/qml/ShortcutProps.qml:155:17: Unable to assign null to QUrl
```

**Comment by robsdedude** [comment]
Fixed. By default you cannot run powershell scripts on Windwos. `You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.`

You have to use `Set-ExecutionPolicy` with a proper choice.
