### ISSUE TITLE
GlosSI JSON bugging when game name includes colon ' : '

### ISSUE THREAD

**Issue by aaacevedo95** [Alia5/GlosSI#145]
As title states, when adding a game that includes a colon (e.g. Yakuza: Like A War) will mess up the `.json`, file located in `\AppData\Roaming\GlosSI\Targets`. 

Can be fixed easily by removing the colon from the title `Yakuza: Like A War` × -> `Yakuza Like A War` ○

**Comment by gbdrbob** [comment]
Same thing happens with Tetris Effect Connected
