### ISSUE TITLE
Glossi non-responsive on select uwp app screen

### ISSUE THREAD

**Issue by mbentham** [Alia5/GlosSI#147]
On Windows 11 when trying to add a UWP app Glossi 0.0.4.1 opens the Select UWP App screen and looks like it is searching for UWP apps but instead it locks completely and becomes non-responsive and does not recover. 

Event viewer reports the following:

Fault bucket , type 0
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: GlosSIConfig.exe
P2: 0.0.4.1
P3: 61d8579a
P4: e4ff
P5: 134217728
P6: 
P7: 
P8: 
P9: 
P10: 

I've attached the windows error report

[Windows Error Report.zip](https://github.com/Alia5/GlosSI/files/8053069/Windows.Error.Report.zip)
 
If glossi has any log files anywhere let me know and I can provide them.

**Comment by Alia5** [comment]
Can you try the latest snapshot build?

https://ci.appveyor.com/project/Alia5/glossi/build/artifacts

**Comment by greyfox95** [comment]
Hi, I am experiencing the same issue on win10 with the snapshot you linked.

Event Viewer File:
[glossicrash.zip](https://github.com/Alia5/GlosSI/files/8191751/glossicrash.zip)

**Comment by Alia5** [comment]
Windows event viewer won't help me much.  
Try running the bundled GetAUMID.ps1 script and check the output

**Comment by greyfox95** [comment]
Okay. I will try that tonight or tomorrow and let you know how it goes.

**Comment by Marocco2** [comment]
> Windows event viewer won't help me much. Try running the bundled GetAUMID.ps1 script and check the output

That file must be unlocked on Windows, otherwise GlosSI will hang

**Comment by Alia5** [comment]
May you try the latest dev-snapshot again?
https://ci.appveyor.com/project/Alia5/glossi/build/artifacts

It should now display an Error instead of hanging.
If the program still hangs, it should take a maximum of 60s

**Comment by sittingmongoose** [comment]
I am also having this issue with the newest build.

**Comment by snarkDADMin** [comment]
Also having this issue with latest build. I'm hoping this is fixable and not a windows limitation. I was hoping to use my XBOX Elite Series 2 with steaminput for UWP games (so the paddles can have unique functions, etc.)

**Comment by sittingmongoose** [comment]
So an update, the dev snapshot you posted fixed the ump listing issue.  I have some other issues and feedback that I will post in a new thread.

**Comment by snarkDADMin** [comment]
I also would like to chime in that the snapshot is enumerating UWP apps for me as well. I had only tried the latest build from the releases page being it was more recent than that comment in this thread.
