### ISSUE TITLE
disable Log Message

### ISSUE THREAD

**Issue by Dr4goonD3mon** [Alia5/GlosSI#150]
## Expected Behavior
it would be nice if there's an option to disable the log notification or shoit only when I launch the game and when it close

## Actual Behavior
the log shows up every time I press the Steam Overlay button

## Steps to Reproduce the Problem

  1. launch a game through GloSI link
  2. Press the Steam Overlay Window, every time the overlay shows up the log notification does it too
...

## Specifications

  - Version: GlosSI Preview 0.0.4.1
  - Platform: Windows 11
  - Subsystem: N/A

**Comment by Alia5** [comment]
I have changed "overlay info" log messages to debug level, and filtered out debug logs when auto showing log.
Should do what you expect in the latest snapshot-build 
https://ci.appveyor.com/project/Alia5/glossi/build/artifacts
