### ISSUE TITLE
A few random issues I discovered

### ISSUE THREAD

**Issue by sittingmongoose** [Alia5/GlosSI#152]
- Version: Newest dev-snapshot
  - Platform: Windows 11, Game pass games, all remote play through Steam Deck.

-With Halo Infinite, you need the xbox app open to launch the game.  If you dont, the game will have a pop up asking you to login to xbox servers, and then fail.

-Back 4 Blood wont recognize controller inputs on Steam deck but it sees the joysticks.  Mouse and Keyboard inputs work.  I tried with and without hide controllers.

-Halo MCC won't launch at all.  It does if I launch it normally though.

-Dead by Daylight works fine, but when i stop the remote stream, it doesnt properly close the game.  My stream ends, but the game is still running on my pc.

**Comment by Alia5** [comment]
> -With Halo Infinite, you need the xbox app open to launch the game. If you dont, the game will have a pop up asking you to login to xbox servers, and then fail.

Doesn't seem like a GlosSI Problem to me? ¯\_(ツ)_/¯

> -Back 4 Blood wont recognize controller inputs on Steam deck but it sees the joysticks. Mouse and Keyboard inputs work. I tried with and without hide controllers.

- Have you tried with/without real device IDs?
- Have you checked there is only a single controller visible in `joy.cpl`

> -Dead by Daylight works fine, but when i stop the remote stream, it doesnt properly close the game. My stream ends, but the game is still running on my pc.

See https://alia5.github.io/GlosSI/ Section: "What this is not"  
`a Steam remote play / steam game streaming solution. (That being said, it can work, but is not guaranteed to.)`
