### ISSUE TITLE
Games with : in the title aren't linked correctly in steam

### ISSUE THREAD

**Issue by SeanFrolander** [Alia5/GlosSI#154]
When adding a game, if the title includes a : (colon), Glossi adds the json file without the colon (since it's an illegal filename character), but adds the game to steam with the launch option to a json file with a colon. So Steam can't open it, since a json file with a colon doesn't exist. 

## Specifications

  - Version: 0.0.5.1
  - Platform: Windows 10

**Comment by Alia5** [comment]
https://1-3-3-7.dev/u/glossisnapshot

Can you try with this?  
I didn't test this, just a quick fix before going to bed >.<  
Snapshot should be ready in about 10 minutes after posting this.

**Comment by Alia5** [comment]
Wow, the build failed due to appveyor updating dependencies.
Just fixed it.
Same link as above, please tell me if it works or not.

**Comment by SeanFrolander** [comment]
It keeps crashing when trying to load the UWP App list
![image](https://user-images.githubusercontent.com/16327808/162473960-34f0ef46-8daf-49a7-a713-5898b94a74d0.png)

**Comment by Alia5** [comment]
Well, that's a different issue.
Keep this on topic, please
