### ISSUE TITLE
SC + Dolphin Emulator = Crazy hdd crash

### ISSUE THREAD

**Issue by dhbtfs** [Alia5/GlosSI#155]
## Expected Behavior
Not crash and play nicely with Dolphin Emulator and my SC pretending to be an Xbox controller

## Actual Behavior
Not hdd crash and 100% usage to a point that you have to press RESET pc button.

## Steps to Reproduce the Problem

  1. Use latest preview version of GlosSI
  2. Use latest dolphin
  3. Add a shortcut to steam (lets call it Xbox controller), we run that so other programs including DE would think its an Xbox controller.)
 4. Just run the button remap and see how slow it is and it freezes for good couple of second.
 5. Play the game...well good luck it crashes dolphin and hdd goes to 100%. No read or right, just 100% active based on task manager hdd performance page.
 6. Try without using your software, game runs smoothly no crash or freeze.
 UPDATE:
Noticed steam freezes too, while steam is installed on SSD C drive.  
Also went on big picture mode and installed Xbox controller drive since it was suggested by your activity page thing, the one that shows controller plugged in and etc

## Specifications

  - Platform: PC win 11 latest + latest preview GlosSI + latest dolphin (try MGS TS)

**Comment by dhbtfs** [comment]
Update:  
I can also confirm that it also crashes my HDD (stucks on 100% usage) when I play it with Forza Horizon 3. Still same setup, Xbxox controller shortcut and running FH3 on its on own. Use SC to navigative through the game, couldn't even load the game. Closed the game and launched it again without SC. Loads in drove for 5 mins, turned on SC, drove for like 20 seconds before the game froze and 100% hdd came back.

**Comment by Alia5** [comment]
Cannot reproduce this.  
I also have Steam installed on SSD and Dolphin(+Games) on a regular old HDD, so that's all pretty similar.
>  I have multiple hdd using windows span to combine them into 1

This is the only difference I can see?

**Comment by dhbtfs** [comment]
How can I show this to you? discord?
GlosSI is copied in Program Files (86) no installed of course, installed the other stuff.
On that HDD I have many games on it, EFT + 10ish Steam games + BF etc...

**Comment by Alia5** [comment]
There should be some Log files in `%appdata%/GlosSI` but I doubt that they would be much help.

Without reproducing or some more digging, I also don't think I can immediately help you. Sorry.

Does this only happen with Dolphin? Is it specific to a game you run with Dolphin, or does it affect everything?

**Comment by dhbtfs** [comment]
[glossitarget.log](https://github.com/Alia5/GlosSI/files/8460088/glossitarget.log)
[glossiconfig.log](https://github.com/Alia5/GlosSI/files/8460089/glossiconfig.log)
![Screenshot 2022-04-10 235237](https://user-images.githubusercontent.com/95389975/162643419-549d83d8-75d2-4ce2-8d37-47eb8de4821e.png)
![Screenshot 2022-04-10 235203](https://user-images.githubusercontent.com/95389975/162643420-a80d49ec-a12e-4c6f-a071-c175a19c010e.png)
![Screenshot 2022-04-10 235314](https://user-images.githubusercontent.com/95389975/162643421-9114a87d-9b44-4d04-a0df-ffc230d21994.png)
Played Forza Horizon 3 for 2 hours on keyboard no issue, as soon as I launched the shortcut for my controller, game recognised it, and after using it for few seconds my hdd went crazy (screenshot provided) I guess with Dolphin it straight crashes, but where as with this FH3 it freezes the world and cars around you until it can load (takes around 30 seconds) and then drive for 1 min until next part of load.  
Any help and info I can provide, ill gladly send.
