### ISSUE TITLE
Launching game with glossi causes significant increase in dwm.exe GPU0 usage, decrease in game GPU1 usage and thus low fps

### ISSUE THREAD

**Issue by Zhurp2020** [Alia5/GlosSI#156]
## Actual Behavior
As the title suggests. When playing Microsoft flight simulator (MSFS) with glossi, desktop windows manager (dwm.exe) takes up to 70% of GPU0 while the game only uses <20% GPU1, resulting in a fps of 5-15. 
## Steps to Reproduce the Problem
I have tried 
a. Launch the game from the Xbox app directly
b. Add the game to steam by glos config and launch the game from steam **without** glossi
c. Add the game to steam by glos config and launch the game from steam **with** glossi
d. Add the Xbox app to steam by glos config and launch the xbox app from steam **with** glossi, then launch the game from xbox app
In a) and b), dwm.exe only uses <20% of GPU0, and the game uses ~70% of GPU1, giving a normal fps of 25-35. But in c and d, the fps is very low. 
## Specifications
System: windows 10
CPU: i7 9750h 
Integrated GPU: UHD 630 (driver: 30.0.101.1660)
dedicated GPU: gtx 1660ti (driver: 30.0.15.1259)

**Comment by Alia5** [comment]
What happens if you set "maxFps" in `%appdata%\GlosSI\Targets\[YOUR_SHORTCUTT_NAME].json` to let's say... 5?
