### ISSUE TITLE
Crash on Windows 11 Home: 22000.708

### ISSUE THREAD

**Issue by hallonbatn** [Alia5/GlosSI#159]
I'm running the latest version of  GlosSI (GlosSI-0.0.6.1) on my newly updated Windows 11 PC (Ver. 22000.708). Now the program starts and closes itself after a few seconds. It is the same version of GlosSI I used flawlessly a few days ago on Win 10.

**Comment by Alia5** [comment]
Log files in `%appdata%\GlosSI`
