### ISSUE TITLE
Access to GloSC

### ISSUE THREAD

**Issue by lucaspimentel** [Alia5/GlosSI#160]
Hello! Current release notes have this note:

> This is a preview build of GloSC successor GlosSI

Is there a way to access GloSC while we wait for GlosSI?

**Comment by Alia5** [comment]
Even in it current form, GlosSI should do the job just fine.

**Comment by lucaspimentel** [comment]
Thanks for clarifying! I was under the impression (from an article I read) that GlosSI had too many issues and GloSC was more stable. I will try GlosSI then if this is what you recommend.
