### ISSUE TITLE
2 controllers added

### ISSUE THREAD

**Issue by svillar13** [Alia5/GlosSI#161]
## Expected Behavior
I want to use glosc for windows game pass games 

## Actual Behavior
After I start notepad through steam and start up a non steam game I notice a notification that it added two xbox 370 controllers. Then certain games like tent shredders revenge starts up two players at the same time.

## Steps to Reproduce the Problem

  1.i start up notepad normally through steam
  2.
  3.
...

## Specifications

  - Version: 2.06 I think I downloaded off the YouTube video link that leads to this website 
  - Platform: steam deck with windows 11 running
  - Subsystem:

**Comment by Alia5** [comment]
You have to have XBox rebinding support enabled in Steam.
Either that, or alternativly, you can limit count of created controllers.
