### ISSUE TITLE
Issue #133 isn't fixed

### ISSUE THREAD

**Issue by CorePoint** [Alia5/GlosSI#162]
https://github.com/Alia5/GlosSI/issues/133 was closed but isn't fixed.
All the titles and paths to exe files of my added 3rd party games were removed, every value stored in the "Start In" field was kept intact.

As somebody else commented that it isn't fixed, but the issue is closed I guessed that you might've overlooked it.

Wish you a good one.

**Comment by Alia5** [comment]
Then re-open it instead of creating a new issue. for crying out loud.

**Comment by CorePoint** [comment]
I thought I only could reopen an issue as the creator of the issue.

As you closed the Issue I thought you already could reproduce it.

Just realized I could've just tagged you in the original issue.

Sorry for the annoyance.

**Comment by CorePoint** [comment]
@Alia5

I thought I only could reopen an issue as the creator of the issue.

As you closed the Issue I thought you already could reproduce it.

Just realized I could've just tagged you in the original issue.

Sorry for the annoyance.
