### ISSUE TITLE
shortcuts.vdf has to be present before using GlosSIConfig.exe

### ISSUE THREAD

**Issue by MafinBoy** [Alia5/GlosSI#163]
## Expected Behavior
`GloSIConfig.exe` should create `shortcuts.vdf` if it is not yet present.

## Actual Behavior
Nothing happens and in logs GlosSI says that a file named `shortcuts.vdf` was not found.

## Steps to Reproduce the Problem

  1. Delete `(steam location)/userdata/(userid)/config/shortcuts.vdf`
  2. Try configuring a game using `GlosSIConfig.exe`

## Specifications

  - Version: GlosSI 0.0.7.0
  - Platform: Windows 10

**Comment by Alia5** [comment]
Please try the latest snapshot build and report back  
https://ci.appveyor.com/project/Alia5/glossi/build/artifacts
