### ISSUE TITLE
No longer able to download release version of GloSC?

### ISSUE THREAD

**Issue by Ferret-Dev** [Alia5/GlosSI#164]
The original version is nowhere to be found, and I am unable to download it. Personally GlosSL doesn't seem to work for me very often, and its kinda annoying that theres now no way for me to access the original GloSC download files anymore.

**Comment by soredake** [comment]
Here [GloSC-installer.zip](https://github.com/Alia5/GlosSI/files/9011783/GloSC-installer.zip)
