### ISSUE TITLE
Games with ® registered trade mark symbol in game name will not launch.

### ISSUE THREAD

**Issue by gbdrbob** [Alia5/GlosSI#166]
## Expected Behavior
Game loads when launched in steam using a GlosSI created entry.

## Actual Behavior
GlosSI opens but game does not launch.

## Steps to Reproduce the Problem

  1. Add a game with a ® registered trade mark symbol in its name (e.g Tetris® Effect: Connected) to Steam using GlosSI
  2. Try to launch game in Steam
  3. Observe that game does not launch

## Specifications

  - Version: 0.0.7.0
  - Platform: Windows 11
  - Subsystem:

If I change the name of the json file in %APPDATA%\GlosSI\Targets to remove the ® and make a matching change to the properties in steam then the game will then launch.

This seems very similar to issues #145 and #154. Though I've not tested it, I expect any games that use the ™ or © symbol in their titles are similarly bugged. Isn’t there a library you can call to sanitise your filenames, rather than try to write your own regex that will likely miss some invalid characters?

**Comment by Alia5** [comment]
Please try the latest snapshot build and report back  
https://ci.appveyor.com/project/Alia5/glossi/build/artifacts

**Comment by gbdrbob** [comment]
> Please try the latest snapshot build and report back https://ci.appveyor.com/project/Alia5/glossi/build/artifacts

Seems to be fixed in [1.0.196](https://ci.appveyor.com/project/Alia5/glossi/builds/44303187) I couldn't try later snapshots as they didn't build.
