### ISSUE TITLE
No joysticks on steam deck 

### ISSUE THREAD

**Issue by gbdrbob** [Alia5/GlosSI#167]
## Expected Behavior
Able to play game with full use of controller inputs, including joysticks

## Actual Behavior
Unable to use joysticks in game

## Steps to Reproduce the Problem

  1. Add a game using GlosSI
  2. Launch game within steam

## Specifications

  - Version: Windows 11
  - Platform: Steam Deck
  - Subsystem:

I have experienced this with three games I've tried so far, Burnout Paradise: Remastered (EA Play), Marvel's Guardians of the Galaxy and Tetris Effect: Connected (Xbox game pass) I've tried both with and without the genuine vid/pid setting.

Tetris effect is playable with just the d-pad and buttons but no joysticks completely breaks Guardians and Burnout

If I manually create an entry for Guardians of the Galaxy in the old GloSC app (by copying the launch command from the GlosSI json file), the game launches and plays with full controls. Same for Burnout but I'm able to directly select the exe as it's an EA Play game.

**Comment by Alia5** [comment]
I don't have SteamDeck so this might be hard to troubleshoot...

1. I'm guessing you have customized the controller config for said shortcuts?
2. Try disabling that:  
![image](https://user-images.githubusercontent.com/3527662/180953961-e60dd20a-fab8-431f-8fbb-c9227ee8f785.png)

**Comment by gbdrbob** [comment]
Thanks, that seems to have fixed things.

**Comment by Alia5** [comment]
Cool! Glad to hear :)

Said checkbox will be defaulted to false (again) in next builds.
