### ISSUE TITLE
Blurry Big Picture Steam overlay.

### ISSUE THREAD

**Issue by LemmusLemmus** [Alia5/GlosSI#168]
## Expected Behavior
Sharp and high resolution Big Picture Steam overlay.

## Actual Behavior
Blurry Big Picture Steam overlay.

## Steps to Reproduce the Problem
  1. Start a GlosSI Steam shortcut with the Big Picture mode overlay.
  2. The Steam popups should be unusually small.
  3. The Steam overlay is of unusually low quality (especially the button icons). It looks like 720p scaled up.

By changing the resolution of `window_.create` in `TargetWindow.cpp` to exactly `desktop_mode.width, desktop_mode.height` the issue disappears. The black screen issue does however return.

If the Steam overlay is started in desktop mode instead, the overlay looks fine.

## Specifications
  - Version: Latest ([0.0.7.0](https://github.com/Alia5/GlosSI/releases/tag/0.0.7.0))
  - Platform: Windows 10
  - Display: 1920x1080, 100% scaling

**Comment by Alia5** [comment]
Hmm... Cannot repro this

**Comment by Alia5** [comment]
Commit https://github.com/Alia5/GlosSI/commit/315a58cfc16d3fcf8641533456e303e972644dcc might improve this.  
No Idea as the BPM overlay is currently broken on AMD GPUs (Thanks Valve/AMD)

**Comment by Alia5** [comment]
New SteamUI will fix this ( soon™ )
