### ISSUE TITLE
Some UWP won't show up

### ISSUE THREAD

**Issue by gnrgui** [Alia5/GlosSI#171]
Some games that I have installed on the Xbox apps are not showing up in the UWP games list.
Here for example:
![image](https://user-images.githubusercontent.com/20758034/185269382-f364c7ee-0213-4f36-9061-cc28ec17f355.png)

![image](https://user-images.githubusercontent.com/20758034/185269490-2b06f663-c0bc-4f6a-8cfe-1cb5879e37c5.png)

![image](https://user-images.githubusercontent.com/20758034/185269513-eb998105-d460-4688-95fa-6751043ec383.png)

Is there a way to fix it? Thanks in advance.

**Comment by gnrgui** [comment]
I was able to puth the path manually for a workaround

**Comment by Alia5** [comment]
See: 5ffc40347a006b5a63306eeba06e4b3389f13d88
