### ISSUE TITLE
Program uses DWM-ExtendFrameBehindClientArea (see description)

### ISSUE THREAD

**Issue by SamuraisEpic** [Alia5/GlosSI#172]
Certain builds of Windows have a bug that clips out anything that uses ExtendFrameBehindClientArea. Though it looks good, my specific build (10.0.22000.1) suffers from this issue, rendering the program unusable, as it seems that the configurator's main interface uses ExtendFrameBehindClientArea. For a potential solution I'd love for there to be a cli argument that allows you to disable it, or to implement a version checker that disables ExtendFrameBehindClientArea below a certain build (i think its 22000.63) similar to the way Valinet tackled the issue in ExplorerPatcher. If i find a fix to the Windows bug on my end, i'll update the issue.

**Comment by Alia5** [comment]
If you find a another way to make a transparent OGL/DirectX rendered window; I'd gladly patch out usage of `ExtendFrameBehindClientArea` ;P

Meanwhile, **you can use** GlosSIs Windowed mode.  
You won't get the Steam Overlay as "overlay" in borderless-windowed applications, but it will be a separate regular old, window, though ;)
