### ISSUE TITLE
shortcuts.vdf keeps deleting itself after using GlosSI

### ISSUE THREAD

**Issue by gnrgui** [Alia5/GlosSI#173]
## Expected Behavior
My steam already have no-steam shortcuts for 82 games. I'm using GlosSi to add my Xbox Game Pass games to use them remotely with a steam link.

## Actual Behavior
Every time that I add the GlosSi shortcuts, when I close the steam client, the shortcuts.vdf file deletes itself, along with all my shortcuts. 

## Steps to Reproduce the Problem

  1. Got more than 80 shorcuts on my steam already
  2. Try to add 30 more with GlosSI
  3. When I restart Steam, the shortcuts.vdf file gets deleted immediately

**I've made a copy of my file before closing steam, a part of it look like this:**

shortcuts  
0 appid Æç©appname Age of Empires IV exe "" StartDir C:\Program Files (x86)\Briano\UWPHook icon  ShortcutPath  LaunchOptions Microsoft.Cardinal_8wekyb3d8bbwe!Game IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime ¬Êc tags  

1 appid n^¸‰appname BattleTech exe "" StartDir C:\Program Files (x86)\Briano\UWPHook icon C:\Program Files\WindowsApps\ParadoxInteractive.Battletech-MainGame_1.9.0.0_x64__zfnrdv2de78ny\Logo-300px.png ShortcutPath  LaunchOptions ParadoxInteractive.Battletech-MainGame_zfnrdv2de78ny!App IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime ¬Êc tags  

2 appid Û`Ôappname Crusader Kings III exe "" StartDir C:\Program Files (x86)\Briano\UWPHook icon C:\Program Files\WindowsApps\ParadoxInteractive.ProjectTitus_1.0.362.0_x64__zfnrdv2de78ny\Square150x150Logo.scale-100.png ShortcutPath  LaunchOptions ParadoxInteractive.ProjectTitus_zfnrdv2de78ny!App IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime ¬Êc tags  

3 appid Ê¬‹µappname Frostpunk exe "" StartDir C:\Program Files (x86)\Briano\UWPHook icon C:\Program Files\WindowsApps\11bitstudios.Frostpunk_1.6.4.2_x64__gwy9gn5q9j1y6\Assets\Square310x310Logo.scale-200.png ShortcutPath  LaunchOptions 11bitstudios.Frostpunk_gwy9gn5q9j1y6!App IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime ¬Êc tags  

4 appid 
NBÃappname Secret Neighbor exe "" StartDir C:\Program Files (x86)\Briano\UWPHook icon C:\Program Files\WindowsApps\tinyBuildGames.SecretNeighbor_1.8.0.0_x64__3sz1pp2ynv2xe\Square150x150Logo.png ShortcutPath  LaunchOptions tinyBuildGames.SecretNeighbor_3sz1pp2ynv2xe!Game IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime ¬Êc tags  

5 appid ¯Ÿ¢Œappname Shenzhen I/O exe "" StartDir C:\Program Files (x86)\Briano\UWPHook icon C:\Program Files\WindowsApps\58020AllianceMetaversalSt.ShenzhenIO_1.0.1.0_x64__j78hpz8e66gfw\LargeLogo.png ShortcutPath  LaunchOptions 58020AllianceMetaversalSt.ShenzhenIO_j78hpz8e66gfw!Shenzhen IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime ¬Êc tags  

6 appid Þ¹¢appname Stellaris exe "" StartDir C:\Program Files (x86)\Briano\UWPHook icon C:\Program Files\WindowsApps\ParadoxInteractive.Stellaris-MicrosoftStoreEdition_3.4.330.0_x64__zfnrdv2de78ny\Square150x150Logo.scale-100.png ShortcutPath  LaunchOptions ParadoxInteractive.Stellaris-MicrosoftStoreEdition_zfnrdv2de78ny!App IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime ¬Êc tags  

7 appid vK ºappname Two Point Hospitalâ„¢ exe "" StartDir C:\Program Files (x86)\Briano\UWPHook icon C:\Program Files\WindowsApps\7904SEGAEuropeLtd.TwoPointHospital-GamePass_1.29.54.0_x64__zs7esxpzd8d5c\GraphicsLogo.png ShortcutPath  LaunchOptions 7904SEGAEuropeLtd.TwoPointHospital-GamePass_zs7esxpzd8d5c!Game IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime ¬Êc tags  

8 appid XŒ7°appname observer_ exe "" StartDir "E:\Amazon Games\Library\ observer_\" icon  ShortcutPath  LaunchOptions  IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags  

9 appid ”aRöappname Ape Out exe "" StartDir "E:\Amazon Games\Library\Ape Out\" icon  ShortcutPath  LaunchOptions  IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags  

10 appid s¯appname Automachef exe "" StartDir "E:\Amazon Games\Library\Automachef\" icon  ShortcutPath  LaunchOptions  IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags  

11 appid ¥óappname Blasphemous exe "" StartDir "E:\Amazon Games\Library\Blasphemous\" icon  ShortcutPath  LaunchOptions  IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags  

12 appid ›B=Çappname Blazing Chrome exe "" StartDir "E:\Amazon Games\Library\Blazing Chrome\" icon  ShortcutPath  LaunchOptions  IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags  

**this go through up to 82 shortcus.
and in the end the GlosSi apps keeps repeting the numbers before appid (and the last two entries dont have numbers bofere appid)**

0 appid «6Šappname Hardspace: Shipbreaker exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\FocusHomeInteractiveSA.HardspaceShipbreaker-PCVers_1.0.21.0_x64__4hny5m903y3g0\Square150x150Logo.png" ShortcutPath  LaunchOptions Hardspace Shipbreaker.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI  

1 appid C
Ã„appname Sea Of Thieves exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\Microsoft.549981C3F5F10_4.2204.13303.0_x64__8wekyb3d8bbwe\Assets\Store\Square150x150Logo.scale-400.png" ShortcutPath  LaunchOptions Sea Of Thieves.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI  

2 appid öY`Øappname Octopath Traveler exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\39EA002F.FrigateMS_1.1.2.0_x64__n746a19ndrrjg\Assets\Logo.png" ShortcutPath  LaunchOptions Octopath Traveler.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI  

3 appid P„appname The Evil Within exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\BethesdaSoftworks.TheEvilWithin-PC_1.4.0.0_x64__3275kfvn8vcwc\TEW1_logo.png" ShortcutPath  LaunchOptions The Evil Within.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI  

4 appid W]îappname Subnautica exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\UnknownWorldsEntertainmen.GAMEPREVIEWSubnautica_1.0.7.0_x64__bh1f6rvenfkm2\Logo.png" ShortcutPath  LaunchOptions Subnautica.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI  

5 appid òðÇappname Road 96 exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\DeepSilver.31214024AC209_1.0.24.0_x64__hmv7qcest37me\Logo.png" ShortcutPath  LaunchOptions Road 96.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI  

6 appid mÓ-ùappname Kentucky Route Zero: TV Edition exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\AnnapurnaInteractive.KentuckyRouteZeroTVEdition_1.0.5.0_x64__c96c51jf6wkvm\KRZ_GameIcon_150x150.png" ShortcutPath  LaunchOptions Kentucky Route Zero TV Edition.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI  

7 appid ëªI³appname Teenage Mutant Ninja Turtles: Shredder's Revenge exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\DotEmu.TeenageMutantNinjaTurtlesShreddersRevenge_1.2207.8.0_x64__map6zyh9ym1xy\Square150x150Logo.png" ShortcutPath  LaunchOptions Teenage Mutant Ninja Turtles Shredder's Revenge.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI  

8 appid GÿÛappname The Ascent exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\CurveDigital.TheAscent_4.8.5.0_x64__1ezqdnbhnc70m\Resources\Logo.png" ShortcutPath  LaunchOptions The Ascent.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI  

9 appid H*yÿappname Trailmakers exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\Flashbulb.Trailmakers_104.3.38616.2_x64__8a41h19xsg1bm\Assets\Square150x150Logo.scale-200.png" ShortcutPath  LaunchOptions Trailmakers.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI    

appid ëy+•appname Trek To Yomi exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\DevolverDigital.TrekToYomiWin10_1.0.7.0_x64__6kzv4j18v0c96\Resources\Logo.png" ShortcutPath  LaunchOptions Trek To Yomi.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI    

appid ¶‹•Šappname Weird West exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "" icon "C:\Program Files\WindowsApps\DevolverDigital.WeirdWestWin10_1.0.72.0_x64__6kzv4j18v0c96\Resources\Logo.png" ShortcutPath  LaunchOptions Weird West.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI    

appid _Ù)Òappname Medieval_Dynasty exe "C:/Users/360gu/Documents/GlosSI-0.0.7.0/GlosSITarget.exe" StartDir "E:/Games/Medieval Dynasty" icon "Medieval_Dynasty" ShortcutPath  LaunchOptions Medieval_Dynasty.json IsHidden     AllowDesktopConfig    AllowOverlay    openvr     Devkit     DevkitGameID  DevkitOverrideAppID     LastPlayTime      tags   Installed locally   GlosSI 

I guess maybe the problem is the order of the numbers? Or perhaps GlosSi won't work if the total number of shortcuts exceeds 100?

...

## Specifications

  - Version: 0.0.7.0
  - Platform: PC
  - Subsystem: Windows

**Comment by Alia5** [comment]
> I guess maybe the problem is the order of the numbers? Or perhaps GlosSi won't work if the total number of shortcuts exceeds 100

Possible.

Can you send me your shortcuts.vdf file directly?  
The Copy&Pasted Ascii gets corrupted here and so is of no use, sadly

**Comment by gnrgui** [comment]
> > I guess maybe the problem is the order of the numbers? Or perhaps GlosSi won't work if the total number of shortcuts exceeds 100
> 
> Possible.
> 
> Can you send me your shortcuts.vdf file directly? The Copy&Pasted Ascii gets corrupted here and so is of no use, sadly

Hi Peter, thanks for working on this and for the reply.
Here is the file:
https://drive.google.com/file/d/1McVhOKgdWCKx-oMnIK_AAFIBYzpJb-Bn/view?usp=sharing
Unfortunately, I don't think that the number of shortcuts is the only problem. Even when I have less shortcuts and try adding more with GlosSI, it breaks the existing ones in Steam. 
The only way I was able to make it work, was creating all the shortcuts that I want to use with GlosSI first, and then adding new ones with steam. As I said, after that, if I try to use GlosSI again to add more, it either breaks all my other shortcuts or corrupt the shortcuts.vdf file, that ends up deleting itself when i reopen Steam. 
Thanks!

**Comment by Alia5** [comment]
Happened when shortcut count was > 100 or tags were used. Fixed now
