### ISSUE TITLE
Does not detect PID of Epic Game Store games

### ISSUE THREAD

**Issue by Zamrod** [Alia5/GlosSI#174]
Added a game from Epic Game Store via URL. Steam opens the game but immediately thinks it has ended and returns to the big picture menu. The game then loads in the background, glossi pops up saying unable to detect PID and then says it is configured to choose when all child processes end. I have the setting set to not close when the process ends for this game to try to get around that but it seems to be ignoring it. 

## Specifications

  - Version: 0.7
  - Platform: Windows 11

**Comment by Alia5** [comment]
Detection for PIDs when launching URLs is not implemented, I'm not sure if it ever will be...

Anyway...  
> I have the setting set to not close when the process ends for this game to try to get around that but it seems to be ignoring it.

Could you provide the `config.json` located in `%appdata%\GlosSI\Targets` as well as the `GlosSITarget.log` ?
