### ISSUE TITLE
Problem with running GlosSi - virtual pad present, no input passthrought

### ISSUE THREAD

**Issue by traczu120** [Alia5/GlosSI#177]
Hello I have a problem of making the GlosSi work at all.

I have a steam deck, Windows 11 fresh install.
I've downloaded v0.8.1 version.

From the downloaded package I have installed (with admin permissions):
-HidHideSetup
-vc_redist.x64 - instalator said that a different version is already installed, so i skipped this.
-ViGEmBusSetup_x64

After that, I ran the Glossi config and added some games.
Example:
![image](https://user-images.githubusercontent.com/55753704/191102145-9f35768d-556b-4f16-9b7e-d2246e35220b.png)

In the general option of controllers in steam i have (sorry for Polish but it is quite simple to understand):
![image](https://user-images.githubusercontent.com/55753704/191102786-c0cf7830-3eb0-4abd-a589-9d33d3c8078c.png)
I've also tested out those options with the same result.

Running this game from a created shortcut in steam creates in device maganer a virtual controller (like old Glosc did):
![image](https://user-images.githubusercontent.com/55753704/191103354-f44fa8ca-2ecd-4302-85b0-87dc1062d718.png)

Unfortunately, none of the added games do not recognise any input from the virtual pad and buttons on the steam deck behave like in desktop mode. 

Without Glossi native steam games work just fine.

What I do wrong?

**Comment by Alia5** [comment]
Please provide logs.  
You can find them in `%appdata%\GlosSI`

**Comment by traczu120** [comment]
[glossitarget.log](https://github.com/Alia5/GlosSI/files/9602058/glossitarget.log)
[glossiconfig.log](https://github.com/Alia5/GlosSI/files/9602059/glossiconfig.log)

Hi thanks for quick answer, i had to readd this game from above again becouse I am still trying to figure it out what is wrong

**Comment by Alia5** [comment]
Did you close the game approx. 20 seconds after GlosSI launched?

Please also try (every setting individually as well as combined):  

- Disable "Close when launched app quits"
- Enable "Use real device IDs" (Set "Max controller count" to 1 when doing this(!))
- Disable "Disable Steam/GlosSI overlay"

**Comment by traczu120** [comment]
Yes i've entered main menu then i closed game, Was it too fast?

Here are logs after tinkering with setting you mentioned (closed games about one min after entering main menu)

Disabled "Close when launched app quits" (due to that option had to kill it in steam after closing the game)
[glossitarget.log](https://github.com/Alia5/GlosSI/files/9602124/glossitarget.log)

Enable "Use real device IDs" (Set "Max controller count" to 1 when doing this(!))
[glossitarget.log](https://github.com/Alia5/GlosSI/files/9602136/glossitarget.log)

Disable "Disable Steam/GlosSI overlay"
[glossitarget.log](https://github.com/Alia5/GlosSI/files/9602145/glossitarget.log)

All combined:
[glossitarget.log](https://github.com/Alia5/GlosSI/files/9602150/glossitarget.log)

In short terms same result

**Comment by Alia5** [comment]
> Yes i've entered main menu then i closed game, Was it too fast?

Nah, just seemed like there could be a bug regarding the detection when the launched app quits, as it was "so quick"  
All good, then


---

Seems about the same in every case...  
Hmm...

Does it work with old GloSC?

---

A couple more things:

You should have a "HidHide configuration client".  
Try opening that **after** you launched the GlosSI-Shortcut (while it's still running) and disable "device hiding" in the devices-tab.  
Also set "Max controller count" to 1 again in GlosSI

Additionally, you might want to uninstall ViGEm completely and specifically try this version
https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.17.333

**Comment by traczu120** [comment]
Hello,

I have an update for you.

I've tested tinkering with "HidHide configuration client" it didn't help

I've installed good old GloSC and it works perfectly like when i was using steam controller :)

BTW I have not install ViGem 1.17. If you want me to I can try it maybe it will help you fix Glossi otherwise I will stay with Glosc.

**Comment by Alia5** [comment]
[GlosSITarget-Snapshot-0.0.8.1-0d6cb49.zip](https://github.com/Alia5/GlosSI/files/9610729/GlosSITarget-Snapshot-0.0.8.1-0d6cb49.zip)

This is the latest GlosSITarget.exe and UWPOverlayenabler.dll from the latest snapshot  
(However built on my machine, not by the CI provider, but shouldn't make a difference)

It includes extended logging and a few other fixes/experiments

Can you try with that?

Please also try to
- just add GlosSITarget to Steam (no config or anything)
- Launch that
- Open/Close Steam overlay in rapid succession to trigger GlosSI overlay
- Optional: Enable UWP Overlay on GlosSI Overlay
- Launch your Game normally via Windows StartMenu or Desktop-Shortcuts (NOT via Steam!)
-  If UWPOverlay wasn't enabled in GlosSI-Overlay: Make sure the UWP game is **not** in fullscreen (can't hurt to not have it fullscreen anyways....)
- See if (virtual) controller is working or not
- Open/Close Steam overlay in rapid succession to trigger GlosSI overlay
- Enable "use real device ids" from withing GlosSI overlay and see if (virtual) controller is working or not

**Comment by arshesney** [comment]
Hi, have the same issue with Steam Controller: it stays in desktop mode.
This is a run that also launches a game (one controller, hide real and use real USB-ID):
[glossitarget.log](https://github.com/Alia5/GlosSI/files/9679854/glossitarget.log)
Using both your snapshot build and ViGem version you linked.

If I launch a blank profile I'm unable to even bring up the overlay.

**Comment by Alia5** [comment]
@arshesney Please try the latest builds from https://glossi.flatspot.pictures

**Comment by arshesney** [comment]
This one works!
I've unzipped the latest build, installed vigemm hidhide from the archive and rebooted.

I've been greeted with two of these messages after:
![image](https://user-images.githubusercontent.com/6453590/193262500-bc639b3d-1faa-4e0f-8918-6a2c5085d3ff.png)

Configured my game like this:
![image](https://user-images.githubusercontent.com/6453590/193262555-5fd84b74-4a19-42ec-aaf3-c72977d35d7a.png)

and controller works fine in game, can access Steam overlay without issues, there are a couple error messages in log
[glossiconfig.log](https://github.com/Alia5/GlosSI/files/9683814/glossiconfig.log)
[glossitarget.log](https://github.com/Alia5/GlosSI/files/9683816/glossitarget.log)
[UWPOverlayEnabler.log](https://github.com/Alia5/GlosSI/files/9683817/UWPOverlayEnabler.log)

**Comment by Alia5** [comment]
> This one works!

Glad to hear that! :)

---

According to the Logs, it seems HidHide is not properly installed.  
You might want to try to get the latest installer from https://github.com/ViGEm/HidHide/releases  

If that still doesn't work, or greets you with the installer error, I'm afraid you have to ask @nefarius  
https://discord.vigem.org/


If you are only using a SteamController/SteamDeck device-hiding (Hide real controllers) is not necessary and can safely be disabled in GlosSIConfig

**Comment by nefarius** [comment]
> If that still doesn't work, or greets you with the installer error, I'm afraid you have to ask @nefarius
> https://discord.vigem.org/

Can't help you with broken MSIs I'm afraid, this is not a HidHide issue but an MSI issue. You're better off googling potential solutions yourself in this case, sorry.

**Comment by Alia5** [comment]
@nefarius
Since I never heard from the user again (after my updates) I assume that his has all been long resolved.

No one else complained, besides :D

**Comment by nefarius** [comment]
Ah, good to know! 🎉
