### ISSUE TITLE
Feature Request: separate option to disable Glossi/Steam Overlay

### ISSUE THREAD

**Issue by RamazanKara** [Alia5/GlosSI#178]
Most of the times I would love to have the Steam Overlay but as the Glossi Config just straight works, do not want to see the Glossi Overlay when clicking twice on the Guide Button. Separating the option to disable Glossi/Steam Overlay would therefore be awesome as it would allow me to keep the Steam Overlay, but disable the Glossi one. 

It would also allow me to really make the Steam Deck a console like experience. Having the glossi overlay available and the logs almost seems unnecessary if it just works.

**Comment by Alia5** [comment]
Sorry, but I don't get the point of this.  
Just don't open/close the SteamOverlay in rapid succession.

I'll leave this issue open, if someone else wants to implement this though I'd be happy to merge

**Comment by LemmusLemmus** [comment]
> Sorry, but I don't get the point of this.  
> Just don't open/close the SteamOverlay in rapid succession.

To be fair, pressing the Steam button in rapid succession is somewhat unavoidable if one for example merely wants to check the overlay clock.

Maybe just changing the time frame for double pressing would suffice?

**Comment by Alia5** [comment]
I've just patched the "forced popup log" a bit.  
Logs now don't force themselves to show in the overlay if they're not at warnings or errors, anymore when at least 20s after launch have passed.  
See: https://github.com/Alia5/GlosSI/commit/046e3bb

Maybe that'll ease this a bit ¯\_(ツ)_/¯

**Comment by Alia5** [comment]
> Maybe just changing the time frame for double pressing would suffice? Either way, it's hardly a major problem.

I don't think that's feasible, as the current timeframe is intentionally quite long (1s).    
Even this can be to short, as the SteamOverlay might take more than a full second to open/close :/

In the initial implementation, you had to open/close the SteamOverlay **twice** in rapid succession  
but that confused some users, soooo... Here we are.

> To be fair, pressing the Steam button in rapid succession is somewhat unavoidable if one for example merely wants to check the overlay clock.

I still don't get the point... Just wait a single second ¯\_(ツ)_/¯

**Comment by RamazanKara** [comment]
> Sorry, but I don't get the point of this.  


Being a developer myself, I understand the point that some additional popup logs and the glossi overlay is pretty irrelevant - I guess when GloSC was first created it was mainly used in combination with the SC, which mainly attracted other Developers.

To further explain my point - nowadays GloSSi is also used with people coming from the Steam Deck Community, which as a fully fledged PC Handheld is often used by other family members or for quick sessions - therefore making any additional logs and overlays impact the user more then it did with the Steam Controller. While this is absolutely not critical, logs and the overlay should be considered as debugging options which can be disabled. Hope I could elaborate my point further and thanks for this awesome tool.

**Comment by Alia5** [comment]
Under that light, I actually do see a point here 😅

> While this is absolutely not critical, logs and the overlay should be considered as debugging options which can be disabled without impacting the steam overlay.

I thought about this, again...

Considering that GlosSI in its current form is a project that stacks one hack on top of another (and it's a cobbled together mess, tbh)...   

I don't know if **now** is the right time **for me** to implement this.   
For a V1? Sure.

I also think I'd be great to at least have "_something_" rendered when GlosSI starts  
Maybe like a splash-screen containing just the GlosSI logo for 1-2 seconds, just so the user gets that GlosSI is active, even if the SteamOverlay bugs out and doesn't render anything.
A fully transparent window is kinda-hard to see 
But I'm not sure yet

As it stands, I probably won't implement this soon

But again, if someone else wants to take on the task, I'd be happy to merge.  
It might even be a good first issue to tackle

---

The basic gist of the implementation would be:

[`SteamTarget::onOverlayChanged`](https://github.com/Alia5/GlosSI/blob/main/GlosSITarget/SteamTarget.cpp#L158) would need to not call `toggleGlossiOverlay()` when configured 
Config parsing is done in [`Settings.h`](https://github.com/Alia5/GlosSI/blob/main/GlosSITarget/Settings.h#L46);  
The `disableOverlay` param has a bit of an ambiguous name, then; However I wouldn't change it to avoid having to write config-file migration code.

Additionally, in [Overlay.cpp](https://github.com/Alia5/GlosSI/blob/main/GlosSITarget/Overlay.cpp#L213) don't append log messages if the GlosSI overlay is disabled and the "forced" popup won't appear anymore.

GlosSIConfig would need some love then, too
[The QML file](https://github.com/Alia5/GlosSI/blob/main/GlosSIConfig/qml/ShortcutProps.qml#L32) and [C++](https://github.com/Alia5/GlosSI/blob/main/GlosSIConfig/UIModel.cpp#L354)

**Comment by Alia5** [comment]
https://github.com/Alia5/GlosSI/commit/472b6c2da490b5fa06118ace8696ba86d05d175b ;)
