### ISSUE TITLE
White screen while trying to open overlay in Big Picture mode

### ISSUE THREAD

**Issue by Marocco2** [Alia5/GlosSI#180]
## Expected Behavior
I should see the Big Picture overlay normally

## Actual Behavior
When I press Shift-Tab I see the screen gradually switch to white. While being completely responsive, it's (of course) humanly unreadable.

## Steps to Reproduce the Problem

  1. Add a UWP game to Steam using GlosSI
  2. Enter Big Picture mode
  3. Play the game
  4. Try to open overlay

## Specifications

  - Version: 9
  - Platform: Win 11 22H2
  - Application: GlosSITarget

## Logs / Additional Files

[logs.zip](https://github.com/Alia5/GlosSI/files/9639302/logs.zip)

**Comment by Alia5** [comment]
Let me guess, you are running on AMD Graphics with a newer version of the GPU driver?

**If so**, this is a Steam/AMD issue and has nothing to do with GlosSI; Please bug Valve/AMD about it.

You can confirm this by running most (if not all) OpenGL bases games that are available directly on Steam like (but not limited to):
- Binding of Isaac Rebirth
- Noita
- Darkest Dungeon
- Prison Architect
- The list goes on...

As a temporary workaround, you can disable usage of the Big-Picture overlay **in Steam**
Alternatively, downgrade your GPU Driver to an older version (I don't know which specific version broke it.)

**Comment by Marocco2** [comment]
Damn

Da: Peter ***@***.***>
Inviato: domenica 25 settembre 2022 00:00
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [Alia5/GlosSI] White screen while trying to open overlay in Big Picture mode (Issue #180)


Let me guess, you are running on AMD Graphics with a newer version of the GPU driver?

If so, this is a Steam/AMD issue and has nothing to do with GlosSI; Please bug Valve/AMD about it.

You can confirm this by running most (if not all) OpenGL bases games that are available directly on Steam like (but not limited to):

  *   Binding of Isaac Rebirth
  *   Noita
  *   Darkest Dungeon
  *   Prison Architect
  *   The list goes on...

As a temporary workaround, you can disable usage of the Big-Picture overlay in Steam
Alternatively, downgrade your GPU Driver to an older version (I don't know which specific version broke it.)

**Comment by Alia5** [comment]
> Damn

Yup 😅

**Comment by Alia5** [comment]
@Marocco2 
Since that's one place that is publicly available for Steam bug reports
https://steamcommunity.com/groups/SteamClientBeta/discussions/0/33737824311964645

You might also want to chime in here

**Comment by Marocco2** [comment]
> @Marocco2 
> Since that's one place that is publicly available for Steam bug reports
> https://steamcommunity.com/groups/SteamClientBeta/discussions/0/33737824311964645
> 
> You might also want to chime in here

Thanks! Gonna check it out

**Comment by Michael-Z-Freeman** [comment]
I just tried the latest Steam Beta that has the Steam Deck UI and this problem is now fixed. Tested in Doom 3 (dhewm3) and Death Stranding (Epic Games) that both suffered from this problem amongst other games.
