### ISSUE TITLE
Add switch pro controller support

### ISSUE THREAD

**Issue by Ultmate-Mario** [Alia5/GlosSI#181]
## Expected Behavior
Accept inputs from a Switch Pro Controller

## Actual Behavior
Accepts no inputs from a Switch Pro Controller

## Steps to Reproduce the Problem

  1. Connect a switch pro controller to your computer
  2. Open a GlosSI game
  3. No inputs
...

## Specifications

  - Version: 0.0.9.1 Snapshot build
  - Platform: Win10
  - Application: GlosSITarget

## Logs / Additional Files
[glossitarget.log](https://github.com/Alia5/GlosSI/files/9660001/glossitarget.log)

(Log and config files are located in `%appdata%/GlosSI`)

Additional Note: Everything works fine with my Dualsense. The issue is lack of Switch Pro Controller support in the program. This was an issue with GlosSC as well.

**Comment by Alia5** [comment]
There is no such thing as Controller XYZ support.  
Everything that Steam Inputs supports, is supported by GlosSI (GlosSI (or GloSC) can't even see the difference!)

Not that "it works on my machine" was ever an argument, but the Switch Pro controller is working fine here, with Minecraft UWP and the config extracted from your log.  
Again, there is no such thing as supporting any particular Input device with GlosSI

---

Is Switch controller support enabled in Steam?
Is the controller layout for that particular shortcut and the Switch Pro Controller specifically setup correctly in Steam?
Different types of controllers may need to be configured separately in Steam.

Additionally, I do see that you are running a snapshot-build of GlosSI (and one that is quite a bit behind)  
Please try to update to the most recent snapshot or try to use the most recent stable version.

You might also want to disable "allow desktop config" for that shortcut while troubleshooting.

**Comment by Ultmate-Mario** [comment]
I'm thinking it's just Minecraft bedrock being stupid. It's probably something wrong with UWP programs becuase just tried it with a regular exe program and it worked just fine.
