### ISSUE TITLE
Trojan detected

### ISSUE THREAD

**Issue by Gadir** [Alia5/GlosSI#186]
Good evening. Funny thing, my antivirus (ESET) shows a trojan in one of your files, and removed it.

;archivo;c:\program files\glossi\glossitarget.exe;una variante de Win64/Agent_AGen.LL Troyano;desinfectado por eliminación;;;88ECC1F9C6DEAA9E248A66D4AE8D586D19E6F81B;05/10/2022 18:55:00

I assume is some kind of code confussin, but it would be nice if you could avoid this alert.

Kind regards.

**Comment by Alia5** [comment]
**Please provide version numbers!**

--


Interesting.  
Just uploaded the latest release as well as the latest snapshot build to virustotal.

[Release](https://www.virustotal.com/gui/file/301eea342d04236c332324b392b07c3133f076b63b9a4460fd1673911f4b5182)
[Snapshot](https://www.virustotal.com/gui/file/065def96ce344b12d908e6e9cac8ac5ffadaf48703b05260ef9972450ca2e419/detection)

Seems like only recent snapshots suffer from this.

In that case, I'll keep that in mind before drafting the next release.  
In the worst case, I'll just have to implement some anti-av measures.
(AVs are useless snake-oil anyway... But I won't tell anyone what to do ¯\_(ツ)_/¯)

**Comment by Alia5** [comment]
Uploaded some more snapshots to virustotal  

Must've come with: 4c78708d9f218b25d267527223ec80f789f26b94

**Comment by Gadir** [comment]
Perfect, thank you very much!
________________________________
De: Peter Repukat ***@***.***>
Enviado: miércoles, 12 de octubre de 2022 1:19
Para: Alia5/GlosSI ***@***.***>
Cc: Gadir ***@***.***>; Author ***@***.***>
Asunto: Re: [Alia5/GlosSI] Trojan detected (Issue #186)


Uploaded some more snapshots to virustotal

Must've come with: 4c78708<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAlia5%2FGlosSI%2Fcommit%2F4c78708d9f218b25d267527223ec80f789f26b94&data=05%7C01%7C%7Cf336ca5910364006e1c708daabdf1e2f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638011272005989503%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lsp3hq2I7Nrw9EcSctOBHJL28208rsAN9pRsQDezy28%3D&reserved=0>

**Comment by Alia5** [comment]
Latest snapshot magically resolves the issue.

https://www.virustotal.com/gui/file/d8b428d6657cb17ed0ed3896b4955d4ddd450d1cde4f93c7706e923fc0e5a10e?nocache=1

Funny... There were no changes in the last commit regarding the SteamTarget.exe
