### ISSUE TITLE
Problem with launching some Epic games through Steam

### ISSUE THREAD

**Issue by George22x** [Alia5/GlosSI#187]
There are some games on Epic Store that cannot be launched if they are added to Steam as a non-Steam game (Borderlands 2 is an example) and must be run directly from the Epic Launcher. This is probably due to DRM. If I add such game to Steam via GlosSI, the result is the same. Could a feature be added to GlosSI to make them run?

**Comment by Alia5** [comment]
Please stick to the issue templates provided.  

Latest snapshot-builds have improved "support" for EGS titles, still experimental, though.  
You should check them out.

**Comment by George22x** [comment]
I tested it with GlosSI 0.1.0.2 with no success.

**Comment by Alia5** [comment]
Qoute:

> Please stick to the issue templates provided.
> 
> Latest snapshot-builds have improved "support" for EGS titles, still experimental, though. You should check them out.

**snapshot-builds**  
**still experimental**

**Comment by George22x** [comment]
Sorry, I overlooked the latest builds. Anyway, this is exactly what I was looking for - with 0.1.0.2-45 build all Epic games I tried now run with GlosSI shortcut in Steam client. Good work, thanks.
