### ISSUE TITLE
Chocolatey package update for new version

### ISSUE THREAD

**Issue by Xav83** [Alia5/GlosSI#190]
Hi @Alia5, :slightly_smiling_face: 

I am the maintainer of GlosSi chocolatey package and I have an issue in order to update the package.
Indeed, up to the version `0.0.8.1`, the releases of GlosSi had an asset named `GlosSI-<version_number>.zip`, which I used in order to create the chocolatey package.

But after this version, the releases do not include any other asset than the code source.
Apparently, you are making your releases available [here](https://glossi.flatspot.pictures/#downloads). Do you plan to make the asset only available on this website, and no more in the asset of the GitHub release ?
If so, it will take some time before I can adjust the chocolatey package construction to that it recovers the asset to this new location :wink: 

Thank you in advance for your answer and your time :slightly_smiling_face:

**Comment by Alia5** [comment]
>  Do you plan to make the asset only available on this website, and no more in the asset of the GitHub release ?

Yup.

> If so, it will take some time before I can adjust the chocolatey package construction to that it recovers the asset to this new location 😉

Hmm... You might run into some trouble there.

Package URL is always: `https://glossi.flatspot.pictures/api/download/GlosSI-<GIT-TAG>.zip`...  
However, you do need to fetch an access token that can be sent using the Auth-Header or query-params beforehand.

Additionally, latest releases do always get flagged by some snake-oil-vendors on Virustotal. https://www.virustotal.com/gui/file/8396e870ae2bc0424a9061cd73cf7418ae6893781b4370fe06a9595e89083ca2?nocache=1

As even dependencies HidHide and steamgrid are affected, I've decided to simply not care about this crap, which might be a show-stopper for you.

**Comment by Xav83** [comment]
I may still try in a few days to adapt the Chocolatey packages.
I feel that it could be a good exercise for me :slightly_smiling_face: 

About Virus Total, it will depend on what the Chocolatey package moderators will decide about what to do if I successfully update the Chocolatey package :wink: 

@Alia5 , in the meantime, do you want me to close this issue, since you won't have to do any modification to do? Everything will be done in my [chocolatey package repository](https://github.com/Xav83/chocolatey-packages).

**Comment by Alia5** [comment]
I'd leave it open, just in case, for now.  
But please notify me as soon as the choco package is updated, or any issues arise ;)

**Comment by Xav83** [comment]
> @Alia5 The package hasn't been able to update itself since 0.0.8.1 https://community.chocolatey.org/packages/glossi

Indeed @superusercode, the version `0.0.8.1` ([GitHub release link](https://github.com/Alia5/GlosSI/releases/tag/0.0.8.1)) was the last one to have the asset `GlosSI-<version-number>.zip`, which is required to generate the Chocolatey package associated with the release. :slightly_smiling_face:

**Comment by Xav83** [comment]
Hi @Alia5,

I hope you are having an amazing day 

I am the maintainer of the [GlosSI Chocolatey package](https://community.chocolatey.org/packages/glossi/0.0.8.1).
I am coming back to this issue in order to check with you, if you want me to create new updated version of the Chocolatey package (requiring either the resources to be available in GitHub releases asset or in a known location I could access), or if you prefer that I discontinue the Chocolatey package for GlosSI ?

Thank you in advance for your answer
