### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by dbryantm** [Alia5/GlosSI#193]
## General Information

  - Version: N/A
  - Platform: Win 11/Steam Deck
  - Controller(s): DualSense
  - Application: N/A
  
## Logs / Additional Files

N/A

## Issue
I was just writing because it seems the website is down so there seems to be no other way to get to the releases. I've already tried going directly to [https://glossi.flatspot.pictures/api/download/GlosSI-0.1.1.1.zip](https://glossi.flatspot.pictures/api/download/GlosSI-0.1.1.1.zip) but that seems broken as well. Thanks in advance!

**Comment by Alia5** [comment]
It's just you.
https://downforeveryoneorjustme.com/glossi.flatspot.pictures
