### ISSUE TITLE
Valorant mouse movement not registering 

### ISSUE THREAD

**Issue by joshuasjung** [Alia5/GlosSI#194]
## Expected Behavior
Being able to use gyro and right joystick to move mouse movement

## Actual Behavior
All buttons working except for mouse

## Steps to Reproduce the Problem

  1. Enable glossi for Valorant. 

...

## General Information

  - Version: 0.1.1.0
  - Platform: Win10 / SteamDeck
  - Controller(s):  Native Steam deck controllers
  - Application: GlosSITarget

## Logs / Additional Files

(Log and config files are located in `%appdata%/GlosSI`)

**Comment by Alia5** [comment]
Am I correct in assuming you use gamepad buttons combined with mouse inputs?  

If so, this is not a GlosSI issue.

**Comment by joshuasjung** [comment]
Correct. wasd and other buttons registering, yet mouse movement does not register even when joystick and trackpad are selected as mouse.

**Comment by Alia5** [comment]
> Correct.

So then the game doesn't support mixed inputs properly it seems.  
Nothing that GlosSI can do for you then.

Try adjusting your steam controller config as with every othe game that doesn't properly support mixed inputs.

Invalid - Closed.
