### ISSUE TITLE
Doesn't play well with steam client beta's new -gamepadui launch option

### ISSUE THREAD

**Issue by dragonfax** [Alia5/GlosSI#196]
The -gamepadui option to steam enables the newer steamdeck style steamos 3.0 interface that steam provides (in the beta steam client only, for now). Its a much better full-screen interface for steam, than the Big Picture Mode. Definitely give it a try.

GlosSI works just fine withe regular steam interface. But if you try to use it with this new steam -gamepadui interface, its very spotty. Only working sometimes. Othertimes, the debug overlay (or whatever you call it) for GlosSI stays up, and never goes away. And something with how GlosSI runs UWP apps, stops the new steam interface from detecting that the game has launched, and we just get a spinning steam icon behind the GlosSI overlay. But you can hear the game running in the background. Its just hidden from view.

* This problem doesn't happen when GlosSI is not used to launch games.
* This problem doesn't happen when using GlosSI with the regular steam interface.
* This issue may exist on non-steamdeck PCs. I have none to test on.

I'm using a steamdeck (windows 10).  And unfortunately steam is the only way to get the buit-in steamdeck controls to work properly. So to use the built-in gamepad for xbox gamepass games, GlosSI is a requirement.

## Expected Behavior

games launch and are playable.

## Actual Behavior

Some overlays appear, and they don't go away. Steam is unable to identify the game is running, and show the game screen.

## Steps to Reproduce the Problem

1. Steamdeck, or potentially another PC.
2. Windows
3. Steam
4. add -gamepadui to steam launch options
5. GlosSI
6. install UWP games
In my case these are xbox gamepass games.
7. launch steam
8. launch games from steam
9. observe that the GlosSI overlay persists, and behind it is a spinning steam icon. No gameplay visuals.
10. There are also various issues trying to quit the game and return to the steam gamepad ui. Often this just hangs.

## General Information

  - Version: (0.1.1.2) - via installer
  - Platform: (Win10 on a steamdeck)
  - Controller(s): (steamdeck)
  - Application: (added to steam using the GlosSI UI, launched from steam)

**Comment by Alia5** [comment]
https://github.com/Alia5/GlosSI/issues/189

It's evolving too quickly to support it currently.

**Comment by dragonfax** [comment]
fair 'nuff

**Comment by Alia5** [comment]
Some users on Discord have reported that the new big picture mode now works well in `0.1.2.0` when excluding the window from the task-list (alt+tab)

**Comment by TheChilliPL** [comment]
I tried every possible combination of settings trying to make it work with Hitman 3 and nothing worked. It worked after I stopped using the `-newbigpicture` option. Now, however, even starting Steam with no additional options, I get the new Big Picture mode, which makes GlosSI unusable for me

**Comment by Alia5** [comment]
Latest GlosSI snapshots(s) work perfectly fine with Valves unfinished new big picture mode, at least for me, you might want to try the latest snapshots.
You can also just not use BPM and be fine.

Without logs, it is neigh impossible to help you, however, as I then cannot possibly have a clue what you're doing and what is happening on your end.
So please provide them.

**Comment by SimplyMav** [comment]
> I tried every possible combination of settings trying to make it work with Hitman 3 and nothing worked. It worked after I stopped using the `-newbigpicture` option. Now, however, even starting Steam with no additional options, I get the new Big Picture mode, which makes GlosSI unusable for me

You can also re-enable the old big picture mode using an "-oldbigpicture" argument the same way the new bpm was enabled before. This option will be removed in a future update but should keep you going in the meantime.

You might also want to check the GlosSI options on Hitman 3 again.
I've noticed that changing some options in GlosSI's global settings will also check the boxes in previously added games, but not actually enable or disable those settings in those games. So I had to go into those games specific GlosSI options and enable, then disable the GlosSI overlay again.
(This was on the latest release version, 1/17/2023. Not sure if Snapshots already fixed this.)

**Comment by TheChilliPL** [comment]
Still doesn't seem to work on the latest snapshot. Overlay is turned off, it's set to not close when the game closes, and to not allow desktop config, but it still uses desktop config all the time, including in-game

**Comment by TheChilliPL** [comment]
Turning on the overlay does make the controller have the game configuration (which I can recognize from the haptic feedback), but the game does not detect anything being pressed
![image](https://user-images.githubusercontent.com/18823939/216668712-8e0d3444-4b36-4105-be06-b68bddccc20c.png)
Starting through Epic Games (by creating a new shortcut with type EGS) does not seem to work at all either

**Comment by Alia5** [comment]
@TheChilliPL 
First of all, it seems like ViGEm and HidHide aren't installed on your system. Without ViGEm and HidHide GlosSI cannot function properly.
Both are bundles with GlosSI and/or can be separately downloaded [here](https://vigem.org/Downloads/)

Additionally, seems you're running on snapshot builds, have you tried stable?

Don't all the read Error messages make you a bit suspicious that there might be something wrong with your setup? ;P

**Comment by TheChilliPL** [comment]
I did try stable, but I admit that after reading I need ViGEm and HidHide installed manually, this piece of information disappeared from my mind completely 💀 thanks  
I'll try installing them soon, see if it works, and report back to you

Could be worth improving the error messages a bit so it's more obvious something needs to be manually installed

**Comment by Alia5** [comment]
As you may have noticed by trying the latest snapshot-builds, there is a new "pre-launch" popup system in place, but obviously it's far from being complete.  
So this is in the works ;)

**Comment by TheChilliPL** [comment]
Uhh, seems like the GlosSI installed ***did*** indeed install ViGEm and HidHide as when I open the installers now, they give me the option to modify the installation, repair it, or uninstall it completely. Not sure why GlosSI doesn't detect them, though

**Comment by TheChilliPL** [comment]
It's still an issue
