### ISSUE TITLE
Option to disable GlosSI overlay while keeping Steam Big Picture ovleray

### ISSUE THREAD

**Issue by louisdefromont** [Alia5/GlosSI#199]
Create an option in GlosSI configurator to disable the GlosSI overlay while keeping the steam overlay. I keep accidentally opening the GlosSI overlay and I have no need for it and the GlosSI boot screen is distracting.

**Comment by louisdefromont** [comment]
I just noticed that this request was already present in issue #178 but for some reason, it got closed?

**Comment by Alia5** [comment]
https://github.com/Alia5/GlosSI/commit/472b6c2da490b5fa06118ace8696ba86d05d175b ;)
