### ISSUE TITLE
Cannot work under Steam offline mode

### ISSUE THREAD

**Issue by anthqiu** [Alia5/GlosSI#201]
## Expected Behavior

When my PC is offline and I logged in under Steam offline mode, GlosSI should work.

## Actual Behavior

It is not working, since Steam will reset HKEY_CURRENT_USER\\SOFTWARE\\Valve\\Steam\\ActiveProcess\\ActiveUser to 0x0, which prevents GlosSI to get the proper user id. (UIModel.cpp:L753)

## Steps to Reproduce the Problem

  1. Disconnect WiFi
  2. Run steam, log in under offline mode
  3. Run GlosSI
...

## General Information

  - master
  - Platform: Win11 21H2 on Steam Deck
  - Controller(s): 1 Steam Controller that comes with the Steam Deck.
  - Application: GlosSIConfig

## Logs / Additional Files

(Log and config files are located in `%appdata%/GlosSI`)

Thanks for creating this awesome project!

**Comment by anthqiu** [comment]
Perhaps a manual override of userid might be handy, since I believe a number of gamers will have only one user profile on their personal device.

**Comment by Alia5** [comment]
Hmm, I seem to cannot reproduce this o.O
Steam writes the registry regardless of Offline/Online-Modes here

However, I've hacked up a fix...  https://github.com/Alia5/GlosSI/commit/9c2b1ad17bcfdc26feb8420c326ac66967b8c99e

`steamPath` and `steamUserId` will now get written to the settings and then used as a fallback if the registry values cannot be read.
Please provide feedback if this works for you or not.  
Snapshot build can be downloaded from: https://glossi.flatspot.pictures (as always)

BTW: It's not just in `UIModel.cpp` ;)

**Comment by Alia5** [comment]
Since I haven't heard otherwise, I assume this is fixed
