### ISSUE TITLE
Error initializing Vigem problem

### ISSUE THREAD

**Issue by STNBPK** [Alia5/GlosSI#206]
## General Information
![微信图片_20230106144731](https://user-images.githubusercontent.com/112117524/210946570-5d6da8a7-4098-4b8a-b40a-66549d6f4f94.png)
 
 It seems that controllers cannot be successfully detected when playing xgp games launched by steam.

**Comment by Alia5** [comment]
Have you *properly* installed ViGEm and HidHide?

**Comment by STNBPK** [comment]
> 

I have installed but not properly maybe. Perhaps I need to redownload them.

**Comment by STNBPK** [comment]
> Have you _properly_ installed ViGEm and HidHide?

Thanks by the way😀

**Comment by Alia5** [comment]
Both (ViGEm and HidHide) are included in the .zip as well as the installer of GlosSI.
If you're having trouble you can always try to get them from https://vigem.org/Downloads/
