### ISSUE TITLE
Having the opposite effect than intended (Hiding steam Xinput controllers)

### ISSUE THREAD

**Issue by corgana** [Alia5/GlosSI#207]
## Expected Behavior

I have three controllers, Xbox, DS4, and Switch Pro.  When I load a program (Cemu for example) to Steam via Glossi, Cemu will "see" three Xinput devices.

## Actual Behavior

When I add Cemu to Steam via Glossi, Cemu "sees" an Xbox, DS4, and Switch Pro controller.

When I add Cemu to Steam via "Add a non steam game to library" menu option, I see three Xinput devices.

## Steps to Reproduce the Problem

  1. Add Cemu to Steam via Glossi using default settings
  2. Open Cemu from Steam
  3. Go into Cemu's controller settings
  4. Select from available controllers
...

## General Information

  - Version: 0.1.1.0
  - Platform: Win11
  - Controller(s): (1 Xbox + 1 DS4 Controller + 1 Switch Pro Controller)
  - Application: (GlosSITarget/GlosSIConfig)

**Comment by Alia5** [comment]
Please provide **LOGS**

**Comment by corgana** [comment]
Happy to oblige. Where are the Glossi log files saved to? A search for "log" in the Glossi install folder and \AppData\Roaming\GlosSI turned up nothing.

Programs I have tested:
CemU: No
Xemu: No
YuZu: No
RPCS3: Appears to work as expected with Glossi
PCSX2: No
Dolphin: No

This is on a fresh Windows 11 install from wiped HD. I had previously used (older version) Glossi with no errors on the same hardware with Windows 10.

**Comment by Alia5** [comment]
The issue-template clearly states:
> (Log and config files are located in `%appdata%/GlosSI`)

The files are called: `glossiconfig.log`, `glossitarget.log`, `GlosSIWatchdog.log` and `UWPOverlayEnabler.log`

Only `glossitarget.log` and `GlosSIWatchdog.log` should be relevant in this case.

> Programs I have tested:
CemU: No
Xemu: No
YuZu: No
RPCS3: Appears to work as expected with Glossi
PCSX2: No
Dolphin: No

At least Dolphin works as expected for me, haven't ran any of the other emulators (ever), though.  
Seems odd...
Makes this even more dependent on logs.

May I ask you then to enable "_Extended Logging_" under "_Advanced_" for **every** GlosSI-Shortcut created? 

---

> A search for "log" in the Glossi install folder and \AppData\Roaming\GlosSI turned up nothing.

...Aaaah Windows 🤦‍♂️😭
Probably due to Windows-search not respecting file-endings if they are hidden (which is the default)
Wellp, at least learned something new...

I'll update the issue templates.

**Comment by corgana** [comment]
Got 'em, thanks. I also forgot to enable "show file extensions" since the install so I was staring _right_ at the log files thinking they were "Text Documents"🙄

Logs attached, I reset everything, moved the old logs and did a fresh test (with Yuzu). Same result. 

[GlosSIWatchdog.log](https://github.com/Alia5/GlosSI/files/10430319/GlosSIWatchdog.log)
[glossitarget.log](https://github.com/Alia5/GlosSI/files/10430320/glossitarget.log)

**Comment by Alia5** [comment]
Seems to me like [HidHide](https://vigem.org/projects/HidHide/) isn't installed or blocked

**Comment by corgana** [comment]
Just FYI I *sort of* figured this out. Hidhide wasn't enabling hiding, AND I didn't realize the new Glossi defaults to one emulated controller per app (I believe it used to be five?) so I was seeing one Xinput thinking it was an an emulated device and falsely believing the rest were being blocked. 

An issue I ran into is that sometimes (seemingly at random, couldn't pin it down), it would create controller 1, 2, 3 etc. Instead of 0, 1, 2 which means that emulators configured to look for Xinput wouldn't see a "player 1".

I tried many reinstalls of Glossi/etc, but couldn't make HidHide actually enable hiding on launch (or figure out why Glossi was skipping controller 0). Eventually I just installed HidHide on it's own, and enabled hiding at boot and added the programs to Steam manually. I have a feeling this is something to do with Win11, because as I said it was working flawlessly on Win10 with the same hardware.

Appreciate the responses I will let you know if I make any more progress.

**Comment by Alia5** [comment]
Funnily enough, I myself had problems with this I've never experienced before, **just in the last hour**.

After some research, Windows update seems to break HidHide sometimes for whatever bullshit reason...
It can be "repaired" though when:

1. Uninstalling HidHide
2. **reboot**
3. Reinstall HidHide
4. **reboot**
