### ISSUE TITLE
UWP Game MSFS Keeps Crashing

### ISSUE THREAD

**Issue by martenumberto** [Alia5/GlosSI#209]
- [x] _**I have read and understand that tickets without Logs (or other info if Logs are 1000% not relevant) will be closed without comment.**_

## Expected Behavior
I wanna use the MSFS on the Steam Deck using Glossi with the Big Picture Mode (New/Old) to customize the Controls easily while gaming (especially L4/5 and R4/5).

## Actual Behavior
MSFS (UWP/MSStore) crashes when using Glossi to use SteamInput. Sometimes it crashes before the Main Menu, sometimes during the Flight Loading Screen and sometimes in a Flight. This doesn't happen if I use native x360 Controller. The Sim doesn't run longer than 10minutes.
The Glossi Settings for the Game doenst matter. I switch between the Options (Seperate Windows, Hide from AppList,...) but it doesn't fix the problem. Even using the Old Steam BigPicture Mode or the "normal" UI doesnt fix that.

## Steps to Reproduce the Problem

  1. Add the MSFS Windows Store Edition to Glossi with default Config.
  2. Add the Shortcut to Steam and restart steam
  3. Launch Steam in BigPictureMode or with Launch Option -GamePadUI
  4. Launch MSFS Glossi from Steam
  5. Try to start a Flight.

## General Information

  - Version: 0.1.2.0
  - Platform: Win11 22h2 on SteamDeck
  - Controller(s): SteamDeck Controls
  - Application: GlossiTarget with MSFS UWP App

## Logs / Additional Files

[GlosSI Logs.zip](https://github.com/Alia5/GlosSI/files/10549411/GlosSI.Logs.zip)

**Edit by maintainer**: Remove embedded logs, zipped archive is enough.
Makes issue virtually unreadable.

**Comment by Alia5** [comment]
Interesting.
According to the logs it's actually *not* M$ FlightSim crashing, but GlosSI(Target).
The GlosSI watchdog then kills FlightSim after GlosSI crashed.

Is there a `glossitarget.dmp` present in the log dir?
I'd need that

**Comment by deWaardt** [comment]
I'm having the exact same issue, with Forza Horizon 5 UWP edition.

My logs are pretty similar to yours. Sometimes I can play for a hour just fine, sometimes it crashes after 5 minutes.
For me what happens, is the game shows "Controller disconnected" and then promptly closes.

I have attached my logfiles and glossitarget.dmp.

[glossitarget.zip](https://github.com/Alia5/GlosSI/files/10609967/glossitarget.zip)

**Comment by Alia5** [comment]
Thanks for the inclusion of the crashdump @deWaardt   
Your particualar crash should be fixed with the next snapshot build :)

**Comment by deWaardt** [comment]
Oh nice! That's fantastic!
