### ISSUE TITLE
A way to get PS4 Controllers work with Steam Remote play while wireless. 

### ISSUE THREAD

**Issue by newdisplayname** [Alia5/GlosSI#210]
- [x ] _**I have read and understand that tickets without Logs (or other info if Logs are 1000% not relevant) will be closed without comment.**_

## General Information

  - Version: (0.1.2.0)
  - Platform: (Win10/Win11 / Desktop/SteamDeck)
  - Controller(s): (PS4-PS5 Controller)
  - Application: (GlosSITarget/GlosSIConfig/Steam Remote Play/Steam Link)
  
Would there be a possible way to get real Dinput PS4-PS5 Controllers to work on GlosSI with Steam Remote Play while wireless and not plugged into the host but from the Client? Using Real Device and Emulate DS4 don't seem to work with Remote Play as it seems it emulates Xinput from Dinput in Remote Play no matter what. So it just doesn't detect in GlosSI, would it be possible just to add a Remote Play option that just does Xinput into Dinput?

**Comment by Alia5** [comment]
> **What GlosSI is not**
> - [...]
> - a Steam remote play / steam game streaming solution. (That being said, it can work, but is not guaranteed to.)
The experience when doing this is most likeley miserable; **Thus there is no support for this use case.**

> [x] I have read and understand that tickets without Logs (or other info if Logs are 1000% not relevant) will be closed without comment.


closed
