### ISSUE TITLE
On Second Launch No Controller Input

### ISSUE THREAD

**Issue by sharinganthief** [Alia5/GlosSI#214]
## Expected Behavior
After successfully launching, playing, and closing an app - on the SECOND launch - the same behavior would occur

## Actual Behavior
After successfully launching, playing, and closing an app - on the SECOND launch - the controller is NOT detected/does not control the launched app

## Steps to Reproduce the Problem

  1. Configure and launch a dolphin gamecube game through steam
[Gotcha Force.json.txt](https://github.com/Alia5/GlosSI/files/10825755/Gotcha.Force.json.txt)

  2. launch/play/close the game
  3. re-launch the game
  4. note that the controller input is not passed through
  5. On steam restart, everything works as expected

## General Information

  - Version: (0.1.2.0)
  - Platform: (Win11)
  - Controller(s): (1 Xbox 360 Conttoller)
  - Application: (GlosSITarget)

## Logs / Additional Files
The files are called: glossiconfig.log, glossitarget.log, GlosSIWatchdog.log and UWPOverlayEnabler.log

[glossiconfig.log](https://github.com/Alia5/GlosSI/files/10825781/glossiconfig.log)
[glossitarget.log](https://github.com/Alia5/GlosSI/files/10825733/glossitarget.log)
[GlosSIWatchdog.log](https://github.com/Alia5/GlosSI/files/10825734/GlosSIWatchdog.log)
[UWPOverlayEnabler.log](https://github.com/Alia5/GlosSI/files/10825735/UWPOverlayEnabler.log)

**Comment by PhantomLiberty** [comment]
I have a similar issue but much much worse. It works on the first launch and then never again. The only way to fix it is to clear my profiles, uninstall and reinstall every component. Only then will it work and only once.
