### ISSUE TITLE
GlosSI cannot use internet shortcuts

### ISSUE THREAD

**Issue by TheBingPlays** [Alia5/GlosSI#215]
## Expected Behavior
Launching game via wemod shortcut to autolaunch game with WeMod Trainer active

## Actual Behavior
GlosSI does not see the game and fails to start

## Steps to Reproduce the Problem

  1. Make a shortcut to desktop with WeMod
  2. Add the shortcut to GlosSI and add to steam
  3. Launch newly made GlosSI shortcut in steam

## General Information
![16775296547305375626322121907351](https://user-images.githubusercontent.com/32751932/221678049-465ab467-ae0f-446a-ab13-28c1702e6468.jpg)

**Comment by TheBingPlays** [comment]
![Screenshot_20230228-164324_Chrome](https://user-images.githubusercontent.com/32751932/221987922-0493afb5-bdb4-49e1-a875-bcd662fb3172.png)
The shortcut is a web url. It has no targets.

**Comment by Alia5** [comment]
Then use the URL directly as path, as that is also supported ;P
