### ISSUE TITLE
Controller works but no vibration

### ISSUE THREAD

**Issue by byzod** [Alia5/GlosSI#216]
## Expected Behavior
Controller works, rumble

## Actual Behavior
Controller works, no rumble

## Steps to Reproduce the Problem

  1. Install Wolong on XGP
  2. Start GlosSIConfig.exe and select Wolong from UWP apps
  3. Apply and restart steam
  4. Start game from steam, goto settings-controls-strength of vibration
  5. The controller should rumble when you change the strength

## General Information

  - Version: GlosSI-Installer-0.1.2.0
  - Platform: Win10 Home x64
  - Controller: Xbox X
  - Application: GlosSITarget

## Logs / Additional Files
[logs.zip](https://github.com/Alia5/GlosSI/files/10890573/logs.zip)

**Comment by Alia5** [comment]
Is this setting enables in Steam?

![image](https://user-images.githubusercontent.com/3527662/222955042-991f6a7f-adb7-4d78-ad6f-938652be39d9.png)

**Comment by byzod** [comment]
Yes, xbox support is also checked
![Snipaste_2023-03-05_18-30-39](https://user-images.githubusercontent.com/848607/222955124-03e82b8c-d47d-4180-8358-147eff8425e5.jpg)

**Comment by byzod** [comment]
@Alia5 is there anything I can do to test or help? I really wanto use glossi with vibration ;(

**Comment by byzod** [comment]
Well I finished wolong....and start another game Shipbreaker, the vibration works for it, so this is a game specific issue

btw the glossi vibration feels different to the vanilla game vibration...hard to describe, the vanilla vibration feels "deeper" or something while the one of glossi feels more "shallow"? 

At least the vibration is different for *this game*

**Comment by Alia5** [comment]
> [...] so this is a game specific issue
> the vanilla vibration feels "deeper" or something while the one of glossi feels more "shallow"?

If I had to guess, that's all Steams "fault."
As GlosSI just forwards what it gets from Steam. There shouldn't be any difference
