### ISSUE TITLE
Use 2 Steam Controllers

### ISSUE THREAD

**Issue by paasklaas** [Alia5/GlosSI#217]
I read that this program was specifically designed for Steam controllers, but the following question also goes for 2 Steam controllers, regardsless that I'm not using original Steam controllers. But I would like to know if this is possible, so when I actually buy 2 Steam controllers there is a change it may work.

I'm Unable to use 2 Switch controllers for an emulator. The emulator only recognizes one controller and it's the controller with which the emulator is started. Tried multiple programs that support 2 controllers. Windows only generates 1 Xbox controller when using GlosSI.

Thank you in advanced for your help.

**Comment by Alia5** [comment]
> I read that this program was specifically designed for Steam controllers

Old GloSC was, GlosSI can be used with any controller that SteamInput supports ;)

> I'm Unable to use 2 Switch controllers for an emulator. 

For GlosSI to create multiple controllers, you have to change the maximum controller count setting for that particular shortcut.   
![image](https://user-images.githubusercontent.com/3527662/223425028-e22b28f2-6deb-4717-a82a-ea8b182f46b3.png)

**Comment by paasklaas** [comment]
Ow Wauw! This is truly amazing. I have been fighting with Steam for days trying to fix it from Steam within, but for some programs it's just impossible. Found your program, asked the question, got the answer and finally.... Got. It. Working! When starting the emulator, Windows detects 2 Xbox controllers and I'm able to use configure them within the emulator.
In my case it works perfectly with 2 no-name-Aliexpress controllers. 

Thank you very very much for this solution!
