### ISSUE TITLE
PS4/5 Remote Play app do not recognize DS4 emulation after latest update

### ISSUE THREAD

**Issue by swnnyh** [Alia5/GlosSI#221]
After the latest update to the PS Remote Play App (ver 6.0.0.2240), the DS4 emulation is not recognized.
RemotePlay.exe is added via the GlosSIConfig, using real device ID and emulate DS4 enabled.
When starting RemotePlay from Steam client, the DS4 controller connected pop-up is displayed
RemotePlay connects to the console, but no input is registered.
With the older version 5.5, the RemotePlay app was working fine using this config (real device ID and emulate DS4 enabled)

Note: The RemotePlay onscreen buttons (start, share and PS) also dont register when clicked (they work fine if the app is launched normally, ie not from the Steam shortcut)

Troubleshooting so far:
Reinstalled GlosSI (uninstall, reboot, reinstall, reboot)
Reinstalled HidHide (uninstall, reboot, reinstall, reboot)
Reinstalled RemotePlay app (uninstall, reboot, reinstall, reboot)
Removed the RemotePlay shortcut and re-added it via GlosSIConfig
Tried with and without real device ID
Disabled Steam overlay, GlosSI overlay and both overlays

## General Information

  - Version: GlosSI 0.1.2.0
  - Platform: Windows 11 on SteamDeck
  - Controller(s): 1 Steam Controller (the Steam Deck Neptune controller)
  - Application: (GlosSITarget/GlosSIConfig)
  
## Logs / Additional Files
[glossiconfig.log](https://github.com/Alia5/GlosSI/files/10948234/glossiconfig.log)
[glossitarget.log](https://github.com/Alia5/GlosSI/files/10948235/glossitarget.log)
[GlosSIWatchdog.log](https://github.com/Alia5/GlosSI/files/10948236/GlosSIWatchdog.log)

**Comment by swnnyh** [comment]
Found a way to rollback to the old RemotePlay ver 5.5, so here are the logs with DS4 emulation working fine:
[glossiconfig.log](https://github.com/Alia5/GlosSI/files/10948290/glossiconfig.log)
[glossitarget.log](https://github.com/Alia5/GlosSI/files/10948292/glossitarget.log)
[GlosSIWatchdog.log](https://github.com/Alia5/GlosSI/files/10948293/GlosSIWatchdog.log)
[UWPOverlayEnabler.log](https://github.com/Alia5/GlosSI/files/10948294/UWPOverlayEnabler.log)

**Comment by Alia5** [comment]
Nothing I can immediately do about.

I'm afraid, you have to bug the guys over at https://github.com/ViGEm/ViGEmBus

In the meantime, as you have already figured out, use an old version of PS RemotePlay
https://github.com/xeropresence/remoteplay-version-patcher
