### ISSUE TITLE
GlosSIConfig crash while loading UWP App list

### ISSUE THREAD

**Issue by olivierDelierre** [Alia5/GlosSI#240]
- [x] _**I have read and understand that tickets without Logs (or other info if Logs are 1000% not relevant) will be closed without comment.**_

## Expected Behavior
Being able to pick an UWP from the list while adding a new UWP App shortcut on GlosSIConfig.

## Actual Behavior
Spinning wheel appears and turn for a few time, and stays blocked, then the program does not respond anymore.

## Steps to Reproduce the Problem

  1. Open GlosSIConfig
  2. Click on the + button to add a new shortcut
  3. Click on UWP App

## General Information

  - Version: 0.1.2.0
  - Platform: Win11
  - Controller(s): N/A
  - Application: GlosSIConfig

## Logs / Additional Files
Attached glossiconfig.log file. The log was deleted before reproducing the bug and generated and filled while executing the steps.
[glossiconfig.log](https://github.com/Alia5/GlosSI/files/14178570/glossiconfig.log)

**Comment by olivierDelierre** [comment]
Also, worth to notice, tried to run the app on Admin mode, and with or without the Xbox app running does not help.

**Comment by Alia5** [comment]
Not maintained anymore.
