### ISSUE TITLE
FH3 not showing video when streamed

### ISSUE THREAD

**Issue by steve1977** [Alia5/GlosSI#50]
I installed GloSC with the objective to play FH3 from Win10 Steam to Moonlight/Raspberry with Xbox One Bluetooth controller.

I still haven't found way to get it working. Three different ways I've tried:

1) Added FH3 manually to Steam, NOT using GloSC - I can stream to Moonlight (video&audio working), but controller not working (acting like a mouse)

2A) Added FH3 to Steam, using GloSC - FH3 does start up, but no video&audio. I see comments about overlay, but just a black/blue screen. It seems that I am stuck with GloSC and the game doesn't launch

2B) Added FH3 to Steam, using GloSC - I can launch the game on my Win server directly from Steam. Cannot test whether controller is working as I don't have controllers connected to the WIndows machine. Whole idea is to have this working with Moonlight stream.

Below the .ini file for trouble-shooting. Thanks for your help!

[BaseConf]
bEnableOverlay=1
bEnableControllers=1
bUseDesktopConfig=0
bHookSteam=true
version=513

[LaunchGame]
bLaunchGame=1
Path=Microsoft.OpusPG_8wekyb3d8bbwe!OpusReleaseFinal
Args=
Type=UWP
bCloseWhenDone=1

**Comment by Alia5** [comment]
GloSC/GlosSI is not a game streaming / steam remote play solution

I'd suggest disabling the overlay 
bEnableOverlay=1
