### ISSUE TITLE
Request: Option to watch for different process than launcher

### ISSUE THREAD

**Issue by Kyahx** [Alia5/GlosSI#53]
For context, I am using GloSC primarily to play Destiny 2.  I have GloSC set to open the Battle.net launcher, which means the overlay keeps running after the game exits (since the B.NET launcher stays open).

Ideally I'd like to add a separate watchdog target than the launcher application, so it can close out when the actual game closes out.

**Comment by Alia5** [comment]
Additionally, GlosSI should auto-detect child processes

**Comment by Alia5** [comment]
At least child processes are somewhat implemented.
This is not really tested, though.
https://github.com/Alia5/GlosSI/commit/8d9771f0ee5bce6ecc77f9c39f1468cfe6327d63

**Comment by mucaho** [comment]
For anyone else wondering how to launch games through the BNet launcher properly: Target the battle net launcher exe and add an additional command line option to automatically open the desired game.

So, for Diablo II: Resurrected i chose `Diablo II Resurrected Launcher.exe` as the target with launch arguments `--exec="launch OSI"` and added both `Battle.net.exe` and `Battle.net Launcher.exe` as launcher processes.

For other games' launch codes (for D2R it's `OSI`), look up the codes in this file: https://github.com/dafzor/bnetlauncher/blob/master/bnetlauncher/Resources/gamesdb.ini

Here's my complete `D2R.json` target configuration:
```
{
    "controller": {
        "allowDesktopConfig": false,
        "emulateDS4": true,
        "maxControllers": 1
    },
    "devices": {
        "hideDevices": true,
        "realDeviceIds": true
    },
    "extendedLogging": false,
    "icon": "D:/BlizzardGames/Diablo II Resurrected/Diablo II Resurrected Launcher.exe",
    "launch": {
        "closeOnExit": false,
        "ignoreLauncher": true,
        "killLauncher": false,
        "launch": true,
        "launchAppArgs": "--exec=\"launch OSI\"",
        "launchPath": "D:/BlizzardGames/Diablo II Resurrected/Diablo II Resurrected Launcher.exe",
        "launcherProcesses": [
            "C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win32\\EpicGamesLauncher.exe",
            "C:\\Program Files (x86)\\Battle.net\\Battle.net.exe",
            "C:\\Program Files (x86)\\Battle.net\\Battle.net Launcher.exe"
        ],
        "waitForChildProcs": true
    },
    "name": "D2R",
    "oldName": "S",
    "snapshotNotify": false,
    "steamPath": "c:/program files (x86)/steam",
    "steamUserId": "REDACTED",
    "version": 1,
    "window": {
        "disableGlosSIOverlay": true,
        "disableOverlay": true,
        "hideAltTab": false,
        "maxFps": null,
        "scale": null,
        "windowMode": false
    }
}

```
