### ISSUE TITLE
Can't use Steam Controller to play a Chrome shortcut game.

### ISSUE THREAD

**Issue by s951736** [Alia5/GlosSI#83]
So I want to use Steam Controller to play a web game, which is Jstris.

First, I made a Chrome shortcut for Jstris, so I can play it in a clean window, and it's easier to get into the site.
Then, I add the Chrome shortcut path to GloSC, which is "C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe" --profile-directory=Default --app-id=icfbgeadpeghpapfjopnkhdadehhcbka"

Then I add this to Steam just as usual.
When I open the game from Steam, it works fine at first, but after about a half-minute, the GloSC cmd window just closes itself, then my Steam Controller go back to desktop mode, the game is still running fine, but I can't use customized control setting to play it after GloSC closes.
This never happened to my other games with GloSC before.

Anyway, how can I properly play a web game using customized controller setting?
And I hope the game can run in Chrome shortcut mode, so it'll more like a native game and having a clean interface.

Thanks.

**Comment by Alia5** [comment]
Can you try https://github.com/Alia5/GlosSI/releases/tag/0.0.2.0
