### ISSUE TITLE
GloSC 2.0.6 still shows empty CMD window after launching till program closes

### ISSUE THREAD

**Issue by Skyyblaze** [Alia5/GlosSI#90]
I just updated to GloSC 2.0.6 and when I launch LD Player (an Android Emulator) through it a empty CMD window still spawns till the program is closed.

It doesn't bother me at all but I thought I would mention it as the changelog for 2.0.6 mentioned that this should be fixed.

**Comment by Ceiyne** [comment]
I have the same issue.  The cmd window closes after I shut down the game, but the GloSC_OverlayWindow stays open and I have to close it manually.  I'm not sure if these are related, expected behavior, or a separate issue.
