### ISSUE TITLE
GloSC SteamTarget process high CPU usage

### ISSUE THREAD

**Issue by idarko** [Alia5/GlosSI#92]
GloSC SteamTarget process puts huge load on CPU if the controller is disconnected due to inactivity. When the controller is connected again process CPU usage immediately returns to normal.

I'm using DS4 over bluetooth and gloSC shortcut with empty executable and global overlay disabled. Processor is i7 4790k. 

CPU usage when gamepad is disconnected: 17%
CPU usage when connected: 0.1%

I'm unable to figure out which version I'm using.
Installer was downloaded on 10/27/2019.

**Comment by Alia5** [comment]
Cannot reproduce in GlosSI
